# Project: Linux_LAUNCHER
# Makefile created by EleStrAnoBaRoN
#character.cppp 2041 et 1888 modifie casts LPCSTR
CPP  = clang++
CC   = gcc
WINDRES = windres.exe
RES  = 
OBJ  = AreaSensitiveEffect.o \
       Assertion.o \
       AsyncFuncQueue.o \
       AutoConfig.o \
       Autolock.o \
       BoostFormula.o \
       Broadcast.o \
       Capuchon.o \
       Character.o \
       ChatterChannels.o \
       Chest.o \
       Clans.o \
       Commands.o \
       CommCenter.o \
       Creatures.o \
       DeadlockDetector.o \
       DebugLockManager.o \
       DebugLoggerAPI.o \
       DebugLogger.o \
       DynamicFlags.o \
       DynObjManager.o \
       EncRandom.o \
       FormatPlayerName.o \
       GAME_RULES.o \
       Group.o \
       Hive.o \
       IntlText.o \
       ItemContainer.o \
       MainConsole.o \
       main.o \
       MemoryManager.o \
       MonsterStructure.o \
       NPCmacroScriptLng.o \
       NPCstructure.o \
       NPC\ Thread.o \
       ObjectListing.o \
       Objects.o \
       ObjectStructure.o \
       ObjectTimer.o \
       ODBCMage.o \
       ODBCTrace.o \
       OldLogger.o \
       PacketManager.o \
       PlayerManager.o \
       PVPSentence.o \
       Rain.o \
       Random.o \
       RegKeyHandler.o \
       ScriptFile.o \
       Setup.o \
       Shutdown.o \
       SimpleMonster.o \
       SimpleNPC.o \
       Skills.o \
       Snow.o \
       SpellEffect.o \
       SpellEffectManager.o \
       SpellMessageHandler.o \
       stackhlp.o \
       StdAfx.o \
       SysopCmd.o \
       System.o \
       System-Win32.o \
       T4CLog.o \
       TextFilter.o \
       TFCException.o \
       TFCInit.o \
       TFC_MAIN.o \
       TFCMessagesHandler.o \
       TFCPacket.o \
       TFCServerGP.o \
       TFCTime.o \
       TFCTimers.o \
       ThreadMonitor.o \
       Timer.o \
       Trade.o \
       Unit.o \
       UnitEffectManager.o \
       Version.o \
       WDAAreaLinks.o \
       WDAClans.o \
       WDACreatures.o \
       WDAFile.o \
       WDAHeader.o \
       WDAHives.o \
       WDALarvae.o \
       WDAObjectsAttrBoosts.o \
       WDAObjectsContainerGroups.o \
       WDAObjectsContainerItems.o \
       WDAObjects.o \
       WDAObjectsSpells.o \
       WDAObjectsWorldObjects.o \
       WDAObjectsWorldObjects.o \
       WDASpellEffects.o \
       WDASpellRequirements.o \
       WDASpells.o \
       WDATable.o \
       WDAWorlds.o \
       WeatherEffect.o \
       WorldMap.o \
       Core/AppStrings.o \
       Core/DebugTools.o \
       crypt/int64stuff.o \
       crypt/keysgestionnar.o \
       NPC_Editor/Assign.o \
       NPC_Editor/Command.o \
       NPC_Editor/CompositeInstruction.o \
       NPC_Editor/ControlFlow.o \
       NPC_Editor/ElseFlow.o \
       NPC_Editor/ElseIfFlow.o \
       NPC_Editor/ForFlow.o \
       NPC_Editor/IfFlow.o \
       NPC_Editor/Instruction.o \
       NPC_Editor/InstructionFactory.o \
       NPC_Editor/Keyword.o \
       NPC_Editor/NPC.o \
       NPC_Editor/NPCManager.o \
       NPC_Editor/RootInstruction.o \
       NPC_Editor/WhileFlow.o \
       Skills/ArmorPenetration.o \
       Skills/CriticalStrike.o \
       Skills/DisarmTrap.o \
       Skills/EvadeView.o \
       Skills/FastHealing.o \
       Skills/FirstAid.o \
       Skills/ForgetPain.o \
       Skills/GenericSkill.o \
       Skills/Hide.o \
       Skills/Meditate.o \
       Skills/Parry.o \
       Skills/Peek.o \
       Skills/PickLock.o \
       Skills/PowerfullBlow.o \
       Skills/Pray.o \
       Skills/Rob.o \
       Skills/Search.o \
       Skills/SkillsRegistration.o \
       Skills/Sneak.o Skills/StunBlow.o \
       Skills/TwoWeapons.o \
       SpellEffects/AttrBoost.o \
       SpellEffects/ConjureEffect.o \
       SpellEffects/DetectHidden.o \
       SpellEffects/DetectInvisibility.o \
       SpellEffects/DispellEffect.o \
       SpellEffects/DrainLife.o \
       SpellEffects/ExhaustEffect.o \
       SpellEffects/FlagAdding.o \
       SpellEffects/HealthEffect.o \
       SpellEffects/Invisibility.o \
       SpellEffects/ItemActionEffect.o \
       SpellEffects/PersistentSpellHookEffect.o \
       SpellEffects/Recall.o \
       SpellEffects/RecallDeathPos.o \
       SpellEffects/SetStatEffect.o \
       SpellEffects/SpellHookEffect.o \
       SpellEffects/SysMsgEffect.o \
       SpellEffects/VaporizeUnit.o \
       TinyXML/tinystr.o \
       TinyXML/tinyxml.o \
       TinyXML/tinyxmlerror.o \
       TinyXML/tinyxmlparser.o \
       UDP/LoopThread.o \
       UDP/Mutex.o \
       UDP/Queue.o \
       UDP/QueueVector.o \
       UDP/Semaphore.o \
       UDP/Thread.o \
       World\ Objects/Armor.o \
       World\ Objects/Book.o \
       World\ Objects/Bow.o \
       World\ Objects/ChestStructure.o \
       World\ Objects/Container.o \
       World\ Objects/DestinyGem.o \
       World\ Objects/Doors.o \
       World\ Objects/Food.o \
       World\ Objects/GemOfLife.o \
       World\ Objects/Gold.o \
       World\ Objects/IcySaber.o \
       World\ Objects/ItemAreaLink.o \
       World\ Objects/ObjectStatsSetup.o \
       World\ Objects/Potions.o \
       World\ Objects/Sign.o \
       World\ Objects/SpellBook.o \
       World\ Objects/StandardObject.o \
       World\ Objects/Sword.o \
       World\ Objects/World\ Objects.o $(RES)
LINKOBJ  = AreaSensitiveEffect.o \
       Assertion.o \
       AsyncFuncQueue.o \
       AutoConfig.o \
       Autolock.o \
       BoostFormula.o \
       Broadcast.o \
       Capuchon.o \
       Character.o \
       ChatterChannels.o \
       Chest.o \
       Clans.o \
       Commands.o \
       CommCenter.o \
       Creatures.o \
       DeadlockDetector.o \
       DebugLockManager.o \
       DebugLoggerAPI.o \
       DebugLogger.o \
       DynamicFlags.o \
       DynObjManager.o \
       EncRandom.o \
       FormatPlayerName.o \
       GAME_RULES.o \
       Group.o \
       Hive.o \
       IntlText.o \
       ItemContainer.o \
       MainConsole.o \
       main.o \
       MemoryManager.o \
       MonsterStructure.o \
       NPCmacroScriptLng.o \
       NPCstructure.o \
       NPC\ Thread.o \
       ObjectListing.o \
       Objects.o \
       ObjectStructure.o \
       ObjectTimer.o \
       ODBCMage.o \
       ODBCTrace.o \
       OldLogger.o \
       PacketManager.o \
       PlayerManager.o \
       PVPSentence.o \
       Rain.o \
       Random.o \
       RegKeyHandler.o \
       ScriptFile.o \
       Setup.o \
       Shutdown.o \
       SimpleMonster.o \
       SimpleNPC.o \
       Skills.o \
       Snow.o \
       SpellEffect.o \
       SpellEffectManager.o \
       SpellMessageHandler.o \
       stackhlp.o \
       StdAfx.o \
       SysopCmd.o \
       System.o \
       System-Win32.o \
       T4CLog.o \
       TextFilter.o \
       TFCException.o \
       TFCInit.o \
       TFC_MAIN.o \
       TFCMessagesHandler.o \
       TFCPacket.o \
       TFCServerGP.o \
       TFCTime.o \
       TFCTimers.o \
       ThreadMonitor.o \
       Timer.o \
       Trade.o \
       Unit.o \
       UnitEffectManager.o \
       Version.o \
       WDAAreaLinks.o \
       WDAClans.o \
       WDACreatures.o \
       WDAFile.o \
       WDAHeader.o \
       WDAHives.o \
       WDALarvae.o \
       WDAObjectsAttrBoosts.o \
       WDAObjectsContainerGroups.o \
       WDAObjectsContainerItems.o \
       WDAObjects.o \
       WDAObjectsSpells.o \
       WDAObjectsWorldObjects.o \
       WDAObjectsWorldObjects.o \
       WDASpellEffects.o \
       WDASpellRequirements.o \
       WDASpells.o \
       WDATable.o \
       WDAWorlds.o \
       WeatherEffect.o \
       WorldMap.o \
       Core/AppStrings.o \
       Core/DebugTools.o \
       crypt/int64stuff.o \
       crypt/keysgestionnar.o \
       NPC_Editor/Assign.o \
       NPC_Editor/Command.o \
       NPC_Editor/CompositeInstruction.o \
       NPC_Editor/ControlFlow.o \
       NPC_Editor/ElseFlow.o \
       NPC_Editor/ElseIfFlow.o \
       NPC_Editor/ForFlow.o \
       NPC_Editor/IfFlow.o \
       NPC_Editor/Instruction.o \
       NPC_Editor/InstructionFactory.o \
       NPC_Editor/Keyword.o \
       NPC_Editor/NPC.o \
       NPC_Editor/NPCManager.o \
       NPC_Editor/RootInstruction.o \
       NPC_Editor/WhileFlow.o \
       Skills/ArmorPenetration.o \
       Skills/CriticalStrike.o \
       Skills/DisarmTrap.o \
       Skills/EvadeView.o \
       Skills/FastHealing.o \
       Skills/FirstAid.o \
       Skills/ForgetPain.o \
       Skills/GenericSkill.o \
       Skills/Hide.o \
       Skills/Meditate.o \
       Skills/Parry.o \
       Skills/Peek.o \
       Skills/PickLock.o \
       Skills/PowerfullBlow.o \
       Skills/Pray.o \
       Skills/Rob.o \
       Skills/Search.o \
       Skills/SkillsRegistration.o \
       Skills/Sneak.o Skills/StunBlow.o \
       Skills/TwoWeapons.o \
       SpellEffects/AttrBoost.o \
       SpellEffects/ConjureEffect.o \
       SpellEffects/DetectHidden.o \
       SpellEffects/DetectInvisibility.o \
       SpellEffects/DispellEffect.o \
       SpellEffects/DrainLife.o \
       SpellEffects/ExhaustEffect.o \
       SpellEffects/FlagAdding.o \
       SpellEffects/HealthEffect.o \
       SpellEffects/Invisibility.o \
       SpellEffects/ItemActionEffect.o \
       SpellEffects/PersistentSpellHookEffect.o \
       SpellEffects/Recall.o \
       SpellEffects/RecallDeathPos.o \
       SpellEffects/SetStatEffect.o \
       SpellEffects/SpellHookEffect.o \
       SpellEffects/SysMsgEffect.o \
       SpellEffects/VaporizeUnit.o \
       TinyXML/tinystr.o \
       TinyXML/tinyxml.o \
       TinyXML/tinyxmlerror.o \
       TinyXML/tinyxmlparser.o \
       UDP/LoopThread.o \
       UDP/Mutex.o \
       UDP/Queue.o \
       UDP/QueueVector.o \
       UDP/Semaphore.o \
       UDP/Thread.o \
       World\ Objects/Armor.o \
       World\ Objects/Book.o \
       World\ Objects/Bow.o \
       World\ Objects/ChestStructure.o \
       World\ Objects/Container.o \
       World\ Objects/DestinyGem.o \
       World\ Objects/Doors.o \
       World\ Objects/Food.o \
       World\ Objects/GemOfLife.o \
       World\ Objects/Gold.o \
       World\ Objects/IcySaber.o \
       World\ Objects/ItemAreaLink.o \
       World\ Objects/ObjectStatsSetup.o \
       World\ Objects/Potions.o \
       World\ Objects/Sign.o \
       World\ Objects/SpellBook.o \
       World\ Objects/StandardObject.o \
       World\ Objects/Sword.o \
       World\ Objects/World\ Objects.o $(RES)
LIBS =  #-lm #-lSDLmain -lSDL -lSDL_image -pthread
INCS =  
CXXINCS = 
BIN  = Linux_SERVER
CXXFLAGS = $(CXXINCS) -g -Wall -Wextra -Werror -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-unused-value -Wno-unused-parameter -Wno-delete-incomplete -Wno-overflow -Wno-int-to-pointer-cast -Wno-implicit-fallthrough -Wno-endif-labels -Wno-comment -Wno-ignored-qualifiers -Wno-reorder -Wno-sign-compare -Wno-c++11-extensions -Wno-missing-declarations -Wno-overloaded-virtual -Wno-uninitialized -Wno-mismatched-new-delete -Wno-unused-private-field -Wno-new-returns-null -Wno-format -Wno-invalid-source-encoding -Wno-c++11-compat-deprecated-writable-strings -Wno-unused-variable -Wno-shift-count-overflow#-fmax-errors=8
CFLAGS = $(INCS)  

.PHONY: all all-before all-after clean clean-custom

all: all-before Linux_SERVER all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Linux_SERVER" $(LIBS)

AreaSensitiveEffect.o: AreaSensitiveEffect.cpp
	$(CPP) -c AreaSensitiveEffect.cpp -o AreaSensitiveEffect.o $(CXXFLAGS)

Assertion.o: Assertion.cpp
	$(CPP) -c Assertion.cpp -o Assertion.o $(CXXFLAGS)

AsyncFuncQueue.o: AsyncFuncQueue.cpp
	$(CPP) -c AsyncFuncQueue.cpp -o AsyncFuncQueue.o $(CXXFLAGS)

AutoConfig.o: AutoConfig.cpp
	$(CPP) -c AutoConfig.cpp -o AutoConfig.o $(CXXFLAGS)

Autolock.o: Autolock.cpp
	$(CPP) -c Autolock.cpp -o Autolock.o $(CXXFLAGS)

BoostFormula.o: BoostFormula.cpp
	$(CPP) -c BoostFormula.cpp -o BoostFormula.o $(CXXFLAGS)

Broadcast.o: Broadcast.cpp
	$(CPP) -c Broadcast.cpp -o Broadcast.o $(CXXFLAGS)

Capuchon.o: Capuchon.cpp
	$(CPP) -c Capuchon.cpp -o Capuchon.o $(CXXFLAGS)

Character.o: Character.cpp
	$(CPP) -c Character.cpp -o Character.o $(CXXFLAGS)

ChatterChannels.o: ChatterChannels.cpp
	$(CPP) -c ChatterChannels.cpp -o ChatterChannels.o $(CXXFLAGS)

Chest.o: Chest.cpp
	$(CPP) -c Chest.cpp -o Chest.o $(CXXFLAGS)

Clans.o: Clans.cpp
	$(CPP) -c Clans.cpp -o Clans.o $(CXXFLAGS)

Commands.o: Commands.cpp
	$(CPP) -c Commands.cpp -o Commands.o $(CXXFLAGS)

CommCenter.o: CommCenter.cpp
	$(CPP) -c CommCenter.cpp -o CommCenter.o $(CXXFLAGS)

Creatures.o: Creatures.cpp
	$(CPP) -c Creatures.cpp -o Creatures.o $(CXXFLAGS)

C_SERVIC.O: C_SERVIC.CPP
	$(CPP) -c C_SERVIC.CPP -o C_SERVIC.O $(CXXFLAGS)

DeadlockDetector.o: DeadlockDetector.cpp
	$(CPP) -c DeadlockDetector.cpp -o DeadlockDetector.o $(CXXFLAGS)

DebugLockManager.o: DebugLockManager.cpp
	$(CPP) -c DebugLockManager.cpp -o DebugLockManager.o $(CXXFLAGS)

DebugLoggerAPI.o: DebugLoggerAPI.cpp
	$(CPP) -c DebugLoggerAPI.cpp -o DebugLoggerAPI.o $(CXXFLAGS)

DebugLogger.o: DebugLogger.cpp
	$(CPP) -c DebugLogger.cpp -o DebugLogger.o $(CXXFLAGS)

DynamicFlags.o: DynamicFlags.cpp
	$(CPP) -c DynamicFlags.cpp -o DynamicFlags.o $(CXXFLAGS)

DynObjManager.o: DynObjManager.cpp
	$(CPP) -c DynObjManager.cpp -o DynObjManager.o $(CXXFLAGS)

EncRandom.o: EncRandom.cpp
	$(CPP) -c EncRandom.cpp -o EncRandom.o $(CXXFLAGS)

EXPFLTR.CPP: EXPFLTR.CP
	$(CPP) -c EXPFLTR.CP -o EXPFLTR.CPP $(CXXFLAGS)

FormatPlayerName.o: FormatPlayerName.cpp
	$(CPP) -c FormatPlayerName.cpp -o FormatPlayerName.o $(CXXFLAGS)

GAME_RULES.o: GAME_RULES.cpp
	$(CPP) -c GAME_RULES.cpp -o GAME_RULES.o $(CXXFLAGS)

Group.o: Group.cpp
	$(CPP) -c Group.cpp -o Group.o $(CXXFLAGS)

Hive.o: Hive.cpp
	$(CPP) -c Hive.cpp -o Hive.o $(CXXFLAGS)

IntlText.o: IntlText.cpp
	$(CPP) -c IntlText.cpp -o IntlText.o $(CXXFLAGS)

ItemContainer.o: ItemContainer.cpp
	$(CPP) -c ItemContainer.cpp -o ItemContainer.o $(CXXFLAGS)

MainConsole.o: MainConsole.cpp
	$(CPP) -c MainConsole.cpp -o MainConsole.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

MemoryManager.o: MemoryManager.cpp
	$(CPP) -c MemoryManager.cpp -o MemoryManager.o $(CXXFLAGS)

MonsterStructure.o: MonsterStructure.cpp
	$(CPP) -c MonsterStructure.cpp -o MonsterStructure.o $(CXXFLAGS)

NPCmacroScriptLng.o: NPCmacroScriptLng.cpp
	$(CPP) -c NPCmacroScriptLng.cpp -o NPCmacroScriptLng.o $(CXXFLAGS)

NPCstructure.o: NPCstructure.cpp
	$(CPP) -c NPCstructure.cpp -o NPCstructure.o $(CXXFLAGS)

NPC\ Thread.o: NPC\ Thread.cpp
	$(CPP) -c NPC\ Thread.cpp -o NPC\ Thread.o $(CXXFLAGS)

ObjectListing.o: ObjectListing.cpp
	$(CPP) -c ObjectListing.cpp -o ObjectListing.o $(CXXFLAGS)

Objects.o: Objects.cpp
	$(CPP) -c Objects.cpp -o Objects.o $(CXXFLAGS)

ObjectStructure.o: ObjectStructure.cpp
	$(CPP) -c ObjectStructure.cpp -o ObjectStructure.o $(CXXFLAGS)

ObjectTimer.o: ObjectTimer.cpp
	$(CPP) -c ObjectTimer.cpp -o ObjectTimer.o $(CXXFLAGS)

ODBCMage.o: ODBCMage.cpp
	$(CPP) -c ODBCMage.cpp -o ODBCMage.o $(CXXFLAGS)

ODBCTrace.o: ODBCTrace.cpp
	$(CPP) -c ODBCTrace.cpp -o ODBCTrace.o $(CXXFLAGS)

OldLogger.o: OldLogger.cpp
	$(CPP) -c OldLogger.cpp -o OldLogger.o $(CXXFLAGS)

PacketManager.o: PacketManager.cpp
	$(CPP) -c PacketManager.cpp -o PacketManager.o $(CXXFLAGS)

PlayerManager.o: PlayerManager.cpp
	$(CPP) -c PlayerManager.cpp -o PlayerManager.o $(CXXFLAGS)

PLAYERS.CPP: PLAYERS.CP
	$(CPP) -c PLAYERS.CP -o PLAYERS.CPP $(CXXFLAGS)

PVPSentence.o: PVPSentence.cpp
	$(CPP) -c PVPSentence.cpp -o PVPSentence.o $(CXXFLAGS)

Rain.o: Rain.cpp
	$(CPP) -c Rain.cpp -o Rain.o $(CXXFLAGS)

Random.o: Random.cpp
	$(CPP) -c Random.cpp -o Random.o $(CXXFLAGS)

RegKeyHandler.o: RegKeyHandler.cpp
	$(CPP) -c RegKeyHandler.cpp -o RegKeyHandler.o $(CXXFLAGS)

ScriptFile.o: ScriptFile.cpp
	$(CPP) -c ScriptFile.cpp -o ScriptFile.o $(CXXFLAGS)

Setup.o: Setup.cpp
	$(CPP) -c Setup.cpp -o Setup.o $(CXXFLAGS)

Shutdown.o: Shutdown.cpp
	$(CPP) -c Shutdown.cpp -o Shutdown.o $(CXXFLAGS)

SimpleMonster.o: SimpleMonster.cpp
	$(CPP) -c SimpleMonster.cpp -o SimpleMonster.o $(CXXFLAGS)

SimpleNPC.o: SimpleNPC.cpp
	$(CPP) -c SimpleNPC.cpp -o SimpleNPC.o $(CXXFLAGS)

Skills.o: Skills.cpp
	$(CPP) -c Skills.cpp -o Skills.o $(CXXFLAGS)

Snow.o: Snow.cpp
	$(CPP) -c Snow.cpp -o Snow.o $(CXXFLAGS)

SpellEffect.o: SpellEffect.cpp
	$(CPP) -c SpellEffect.cpp -o SpellEffect.o $(CXXFLAGS)

SpellEffectManager.o: SpellEffectManager.cpp
	$(CPP) -c SpellEffectManager.cpp -o SpellEffectManager.o $(CXXFLAGS)

SpellMessageHandler.o: SpellMessageHandler.cpp
	$(CPP) -c SpellMessageHandler.cpp -o SpellMessageHandler.o $(CXXFLAGS)

stackhlp.o: stackhlp.cpp
	$(CPP) -c stackhlp.cpp -o stackhlp.o $(CXXFLAGS)

StdAfx.o: StdAfx.cpp
	$(CPP) -c StdAfx.cpp -o StdAfx.o $(CXXFLAGS)

SysopCmd.o: SysopCmd.cpp
	$(CPP) -c SysopCmd.cpp -o SysopCmd.o $(CXXFLAGS)

System.o: System.cpp
	$(CPP) -c System.cpp -o System.o $(CXXFLAGS)

System-Win32.o: System-Win32.cpp
	$(CPP) -c System-Win32.cpp -o System-Win32.o $(CXXFLAGS)

T4CLog.o: T4CLog.cpp
	$(CPP) -c T4CLog.cpp -o T4CLog.o $(CXXFLAGS)

TextFilter.o: TextFilter.cpp
	$(CPP) -c TextFilter.cpp -o TextFilter.o $(CXXFLAGS)

TFCException.o: TFCException.cpp
	$(CPP) -c TFCException.cpp -o TFCException.o $(CXXFLAGS)

TFCInit.o: TFCInit.cpp
	$(CPP) -c TFCInit.cpp -o TFCInit.o $(CXXFLAGS)

TFC_MAIN.o: TFC_MAIN.cpp
	$(CPP) -c TFC_MAIN.cpp -o TFC_MAIN.o $(CXXFLAGS)

TFCMessagesHandler.o: TFCMessagesHandler.cpp
	$(CPP) -c TFCMessagesHandler.cpp -o TFCMessagesHandler.o $(CXXFLAGS)

TFCPacket.o: TFCPacket.cpp
	$(CPP) -c TFCPacket.cpp -o TFCPacket.o $(CXXFLAGS)

TFCServerGP.o: TFCServerGP.cpp
	$(CPP) -c TFCServerGP.cpp -o TFCServerGP.o $(CXXFLAGS)

TFCTime.o: TFCTime.cpp
	$(CPP) -c TFCTime.cpp -o TFCTime.o $(CXXFLAGS)

TFCTimers.o: TFCTimers.cpp
	$(CPP) -c TFCTimers.cpp -o TFCTimers.o $(CXXFLAGS)

ThreadMonitor.o: ThreadMonitor.cpp
	$(CPP) -c ThreadMonitor.cpp -o ThreadMonitor.o $(CXXFLAGS)

Timer.o: Timer.cpp
	$(CPP) -c Timer.cpp -o Timer.o $(CXXFLAGS)

Trade.o: Trade.cpp
	$(CPP) -c Trade.cpp -o Trade.o $(CXXFLAGS)

Unit.o: Unit.cpp
	$(CPP) -c Unit.cpp -o Unit.o $(CXXFLAGS)

UnitEffectManager.o: UnitEffectManager.cpp
	$(CPP) -c UnitEffectManager.cpp -o UnitEffectManager.o $(CXXFLAGS)

Version.o: Version.cpp
	$(CPP) -c Version.cpp -o Version.o $(CXXFLAGS)

WDAAreaLinks.o: WDAAreaLinks.cpp
	$(CPP) -c WDAAreaLinks.cpp -o WDAAreaLinks.o $(CXXFLAGS)

WDAClans.o: WDAClans.cpp
	$(CPP) -c WDAClans.cpp -o WDAClans.o $(CXXFLAGS)

WDACreatures.o: WDACreatures.cpp
	$(CPP) -c WDACreatures.cpp -o WDACreatures.o $(CXXFLAGS)

WDAFile.o: WDAFile.cpp
	$(CPP) -c WDAFile.cpp -o WDAFile.o $(CXXFLAGS)

WDAHeader.o: WDAHeader.cpp
	$(CPP) -c WDAHeader.cpp -o WDAHeader.o $(CXXFLAGS)

WDAHives.o: WDAHives.cpp
	$(CPP) -c WDAHives.cpp -o WDAHives.o $(CXXFLAGS)

WDALarvae.o: WDALarvae.cpp
	$(CPP) -c WDALarvae.cpp -o WDALarvae.o $(CXXFLAGS)

WDAObjectsAttrBoosts.o: WDAObjectsAttrBoosts.cpp
	$(CPP) -c WDAObjectsAttrBoosts.cpp -o WDAObjectsAttrBoosts.o $(CXXFLAGS)

WDAObjectsContainerGroups.o: WDAObjectsContainerGroups.cpp
	$(CPP) -c WDAObjectsContainerGroups.cpp -o WDAObjectsContainerGroups.o $(CXXFLAGS)

WDAObjectsContainerItems.o: WDAObjectsContainerItems.cpp
	$(CPP) -c WDAObjectsContainerItems.cpp -o WDAObjectsContainerItems.o $(CXXFLAGS)

WDAObjects.o: WDAObjects.cpp
	$(CPP) -c WDAObjects.cpp -o WDAObjects.o $(CXXFLAGS)

WDAObjectsSpells.o: WDAObjectsSpells.cpp
	$(CPP) -c WDAObjectsSpells.cpp -o WDAObjectsSpells.o $(CXXFLAGS)

WDAObjectsWorldObjects.o: WDAObjectsWorldObjects.cpp
	$(CPP) -c WDAObjectsWorldObjects.cpp -o WDAObjectsWorldObjects.o $(CXXFLAGS)

WDASpellEffects.o: WDASpellEffects.cpp
	$(CPP) -c WDASpellEffects.cpp -o WDASpellEffects.o $(CXXFLAGS)

WDASpellRequirements.o: WDASpellRequirements.cpp
	$(CPP) -c WDASpellRequirements.cpp -o WDASpellRequirements.o $(CXXFLAGS)

WDASpells.o: WDASpells.cpp
	$(CPP) -c WDASpells.cpp -o WDASpells.o $(CXXFLAGS)

WDATable.o: WDATable.cpp
	$(CPP) -c WDATable.cpp -o WDATable.o $(CXXFLAGS)

WDAWorlds.o: WDAWorlds.cpp
	$(CPP) -c WDAWorlds.cpp -o WDAWorlds.o $(CXXFLAGS)

WeatherEffect.o: WeatherEffect.cpp
	$(CPP) -c WeatherEffect.cpp -o WeatherEffect.o $(CXXFLAGS)

WorldMap.o: WorldMap.cpp
	$(CPP) -c WorldMap.cpp -o WorldMap.o $(CXXFLAGS)

Core/AppStrings.o: Core/AppStrings.cpp
	$(CPP) -c Core/AppStrings.cpp -o Core/AppStrings.o $(CXXFLAGS)

Core/DebugTools.o: Core/DebugTools.cpp
	$(CPP) -c Core/DebugTools.cpp -o Core/DebugTools.o $(CXXFLAGS)

crypt/int64stuff.o: crypt/int64stuff.cpp
	$(CPP) -c crypt/int64stuff.cpp -o crypt/int64stuff.o $(CXXFLAGS)

crypt/keysgestionnar.o: crypt/keysgestionnar.cpp
	$(CPP) -c crypt/keysgestionnar.cpp -o crypt/keysgestionnar.o $(CXXFLAGS)

NPC_Editor/Assign.o: NPC_Editor/Assign.cpp
	$(CPP) -c NPC_Editor/Assign.cpp -o NPC_Editor/Assign.o $(CXXFLAGS)

NPC_Editor/Command.o: NPC_Editor/Command.cpp
	$(CPP) -c NPC_Editor/Command.cpp -o NPC_Editor/Command.o $(CXXFLAGS)

NPC_Editor/CompositeInstruction.o: NPC_Editor/CompositeInstruction.cpp
	$(CPP) -c NPC_Editor/CompositeInstruction.cpp -o NPC_Editor/CompositeInstruction.o $(CXXFLAGS)

NPC_Editor/ControlFlow.o: NPC_Editor/ControlFlow.cpp
	$(CPP) -c NPC_Editor/ControlFlow.cpp -o NPC_Editor/ControlFlow.o $(CXXFLAGS)

NPC_Editor/ElseFlow.o: NPC_Editor/ElseFlow.cpp
	$(CPP) -c NPC_Editor/ElseFlow.cpp -o NPC_Editor/ElseFlow.o $(CXXFLAGS)

NPC_Editor/ElseIfFlow.o: NPC_Editor/ElseIfFlow.cpp
	$(CPP) -c NPC_Editor/ElseIfFlow.cpp -o NPC_Editor/ElseIfFlow.o $(CXXFLAGS)

NPC_Editor/ForFlow.o: NPC_Editor/ForFlow.cpp
	$(CPP) -c NPC_Editor/ForFlow.cpp -o NPC_Editor/ForFlow.o $(CXXFLAGS)

NPC_Editor/IfFlow.o: NPC_Editor/IfFlow.cpp
	$(CPP) -c NPC_Editor/IfFlow.cpp -o NPC_Editor/IfFlow.o $(CXXFLAGS)

NPC_Editor/Instruction.o: NPC_Editor/Instruction.cpp
	$(CPP) -c NPC_Editor/Instruction.cpp -o NPC_Editor/Instruction.o $(CXXFLAGS)

NPC_Editor/InstructionFactory.o: NPC_Editor/InstructionFactory.cpp
	$(CPP) -c NPC_Editor/InstructionFactory.cpp -o NPC_Editor/InstructionFactory.o $(CXXFLAGS)

NPC_Editor/Keyword.o: NPC_Editor/Keyword.cpp
	$(CPP) -c NPC_Editor/Keyword.cpp -o NPC_Editor/Keyword.o $(CXXFLAGS)

NPC_Editor/NPC.o: NPC_Editor/NPC.cpp
	$(CPP) -c NPC_Editor/NPC.cpp -o NPC_Editor/NPC.o $(CXXFLAGS)

NPC_Editor/NPCManager.o: NPC_Editor/NPCManager.cpp
	$(CPP) -c NPC_Editor/NPCManager.cpp -o NPC_Editor/NPCManager.o $(CXXFLAGS)

NPC_Editor/RootInstruction.o: NPC_Editor/RootInstruction.cpp
	$(CPP) -c NPC_Editor/RootInstruction.cpp -o NPC_Editor/RootInstruction.o $(CXXFLAGS)

NPC_Editor/WhileFlow.o: NPC_Editor/WhileFlow.cpp
	$(CPP) -c NPC_Editor/WhileFlow.cpp -o NPC_Editor/WhileFlow.o $(CXXFLAGS)

Skills/ArmorPenetration.o: Skills/ArmorPenetration.cpp
	$(CPP) -c Skills/ArmorPenetration.cpp -o Skills/ArmorPenetration.o $(CXXFLAGS)

Skills/CriticalStrike.o: Skills/CriticalStrike.cpp
	$(CPP) -c Skills/CriticalStrike.cpp -o Skills/CriticalStrike.o $(CXXFLAGS)

Skills/DisarmTrap.o: Skills/DisarmTrap.cpp
	$(CPP) -c Skills/DisarmTrap.cpp -o Skills/DisarmTrap.o $(CXXFLAGS)

Skills/EvadeView.o: Skills/EvadeView.cpp
	$(CPP) -c Skills/EvadeView.cpp -o Skills/EvadeView.o $(CXXFLAGS)

Skills/FastHealing.o: Skills/FastHealing.cpp
	$(CPP) -c Skills/FastHealing.cpp -o Skills/FastHealing.o $(CXXFLAGS)

Skills/FirstAid.o: Skills/FirstAid.cpp
	$(CPP) -c Skills/FirstAid.cpp -o Skills/FirstAid.o $(CXXFLAGS)

Skills/ForgetPain.o: Skills/ForgetPain.cpp
	$(CPP) -c Skills/ForgetPain.cpp -o Skills/ForgetPain.o $(CXXFLAGS)

Skills/GenericSkill.o: Skills/GenericSkill.cpp
	$(CPP) -c Skills/GenericSkill.cpp -o Skills/GenericSkill.o $(CXXFLAGS)

Skills/Hide.o: Skills/Hide.cpp
	$(CPP) -c Skills/Hide.cpp -o Skills/Hide.o $(CXXFLAGS)

Skills/Meditate.o: Skills/Meditate.cpp
	$(CPP) -c Skills/Meditate.cpp -o Skills/Meditate.o $(CXXFLAGS)

Skills/Parry.o: Skills/Parry.cpp
	$(CPP) -c Skills/Parry.cpp -o Skills/Parry.o $(CXXFLAGS)

Skills/Peek.o: Skills/Peek.cpp
	$(CPP) -c Skills/Peek.cpp -o Skills/Peek.o $(CXXFLAGS)

Skills/PickLock.o: Skills/PickLock.cpp
	$(CPP) -c Skills/PickLock.cpp -o Skills/PickLock.o $(CXXFLAGS)

Skills/PowerfullBlow.o: Skills/PowerfullBlow.cpp
	$(CPP) -c Skills/PowerfullBlow.cpp -o Skills/PowerfullBlow.o $(CXXFLAGS)

Skills/Pray.o: Skills/Pray.cpp
	$(CPP) -c Skills/Pray.cpp -o Skills/Pray.o $(CXXFLAGS)

Skills/Rob.o: Skills/Rob.cpp
	$(CPP) -c Skills/Rob.cpp -o Skills/Rob.o $(CXXFLAGS)

Skills/Search.o: Skills/Search.cpp
	$(CPP) -c Skills/Search.cpp -o Skills/Search.o $(CXXFLAGS)

Skills/SkillsRegistration.o: Skills/SkillsRegistration.cpp
	$(CPP) -c Skills/SkillsRegistration.cpp -o Skills/SkillsRegistration.o $(CXXFLAGS)

Skills/Sneak.o: Skills/Sneak.cpp
	$(CPP) -c Skills/Sneak.cpp -o Skills/Sneak.o $(CXXFLAGS)

Skills/TwoWeapons.o: Skills/TwoWeapons.cpp
	$(CPP) -c Skills/TwoWeapons.cpp -o Skills/TwoWeapons.o $(CXXFLAGS)

SpellEffects/AttrBoost.o: SpellEffects/AttrBoost.cpp
	$(CPP) -c SpellEffects/AttrBoost.cpp -o SpellEffects/AttrBoost.o $(CXXFLAGS)

SpellEffects/ConjureEffect.o: SpellEffects/ConjureEffect.cpp
	$(CPP) -c SpellEffects/ConjureEffect.cpp -o SpellEffects/ConjureEffect.o $(CXXFLAGS)

SpellEffects/DetectHidden.o: SpellEffects/DetectHidden.cpp
	$(CPP) -c SpellEffects/DetectHidden.cpp -o SpellEffects/DetectHidden.o $(CXXFLAGS)

SpellEffects/DetectInvisibility.o: SpellEffects/DetectInvisibility.cpp
	$(CPP) -c SpellEffects/DetectInvisibility.cpp -o SpellEffects/DetectInvisibility.o $(CXXFLAGS)

SpellEffects/DispellEffect.o: SpellEffects/DispellEffect.cpp
	$(CPP) -c SpellEffects/DispellEffect.cpp -o SpellEffects/DispellEffect.o $(CXXFLAGS)

SpellEffects/DrainLife.o: SpellEffects/DrainLife.cpp
	$(CPP) -c SpellEffects/DrainLife.cpp -o SpellEffects/DrainLife.o $(CXXFLAGS)

SpellEffects/ExhaustEffect.o: SpellEffects/ExhaustEffect.cpp
	$(CPP) -c SpellEffects/ExhaustEffect.cpp -o SpellEffects/ExhaustEffect.o $(CXXFLAGS)

SpellEffects/FlagAdding.o: SpellEffects/FlagAdding.cpp
	$(CPP) -c SpellEffects/FlagAdding.cpp -o SpellEffects/FlagAdding.o $(CXXFLAGS)

SpellEffects/HealthEffect.o: SpellEffects/HealthEffect.cpp
	$(CPP) -c SpellEffects/HealthEffect.cpp -o SpellEffects/HealthEffect.o $(CXXFLAGS)

SpellEffects/Invisibility.o: SpellEffects/Invisibility.cpp
	$(CPP) -c SpellEffects/Invisibility.cpp -o SpellEffects/Invisibility.o $(CXXFLAGS)

SpellEffects/ItemActionEffect.o: SpellEffects/ItemActionEffect.cpp
	$(CPP) -c SpellEffects/ItemActionEffect.cpp -o SpellEffects/ItemActionEffect.o $(CXXFLAGS)

SpellEffects/PersistentSpellHookEffect.o: SpellEffects/PersistentSpellHookEffect.cpp
	$(CPP) -c SpellEffects/PersistentSpellHookEffect.cpp -o SpellEffects/PersistentSpellHookEffect.o $(CXXFLAGS)

SpellEffects/Recall.o: SpellEffects/Recall.cpp
	$(CPP) -c SpellEffects/Recall.cpp -o SpellEffects/Recall.o $(CXXFLAGS)

SpellEffects/RecallDeathPos.o: SpellEffects/RecallDeathPos.cpp
	$(CPP) -c SpellEffects/RecallDeathPos.cpp -o SpellEffects/RecallDeathPos.o $(CXXFLAGS)

SpellEffects/SetStatEffect.o: SpellEffects/SetStatEffect.cpp
	$(CPP) -c SpellEffects/SetStatEffect.cpp -o SpellEffects/SetStatEffect.o $(CXXFLAGS)

SpellEffects/SpellHookEffect.o: SpellEffects/SpellHookEffect.cpp
	$(CPP) -c SpellEffects/SpellHookEffect.cpp -o SpellEffects/SpellHookEffect.o $(CXXFLAGS)

SpellEffects/SysMsgEffect.o: SpellEffects/SysMsgEffect.cpp
	$(CPP) -c SpellEffects/SysMsgEffect.cpp -o SpellEffects/SysMsgEffect.o $(CXXFLAGS)

SpellEffects/VaporizeUnit.o: SpellEffects/VaporizeUnit.cpp
	$(CPP) -c SpellEffects/VaporizeUnit.cpp -o SpellEffects/VaporizeUnit.o $(CXXFLAGS)

TinyXML/tinystr.o: TinyXML/tinystr.cpp
	$(CPP) -c TinyXML/tinystr.cpp -o TinyXML/tinystr.o $(CXXFLAGS)

TinyXML/tinyxml.o: TinyXML/tinyxml.cpp
	$(CPP) -c TinyXML/tinyxml.cpp -o TinyXML/tinyxml.o $(CXXFLAGS)

TinyXML/tinyxmlerror.o: TinyXML/tinyxmlerror.cpp
	$(CPP) -c TinyXML/tinyxmlerror.cpp -o TinyXML/tinyxmlerror.o $(CXXFLAGS)

TinyXML/tinyxmlparser.o: TinyXML/tinyxmlparser.cpp
	$(CPP) -c TinyXML/tinyxmlparser.cpp -o TinyXML/tinyxmlparser.o $(CXXFLAGS)

UDP/LoopThread.o: UDP/LoopThread.cpp
	$(CPP) -c UDP/LoopThread.cpp -o UDP/LoopThread.o $(CXXFLAGS)

UDP/Mutex.o: UDP/Mutex.cpp
	$(CPP) -c UDP/Mutex.cpp -o UDP/Mutex.o $(CXXFLAGS)

UDP/Queue.o: UDP/Queue.cpp
	$(CPP) -c UDP/Queue.cpp -o UDP/Queue.o $(CXXFLAGS)

UDP/QueueVector.o: UDP/QueueVector.cpp
	$(CPP) -c UDP/QueueVector.cpp -o UDP/QueueVector.o $(CXXFLAGS)

UDP/Semaphore.o: UDP/Semaphore.cpp
	$(CPP) -c UDP/Semaphore.cpp -o UDP/Semaphore.o $(CXXFLAGS)

UDP/Thread.o: UDP/Thread.cpp
	$(CPP) -c UDP/Thread.cpp -o UDP/Thread.o $(CXXFLAGS)

World\ Objects/Armor.o: World\ Objects/Armor.cpp
	$(CPP) -c World\ Objects/Armor.cpp -o World\ Objects/Armor.o $(CXXFLAGS)

World\ Objects/Book.o: World\ Objects/Book.cpp
	$(CPP) -c World\ Objects/Book.cpp -o World\ Objects/Book.o $(CXXFLAGS)

World\ Objects/Bow.o: World\ Objects/Bow.cpp
	$(CPP) -c World\ Objects/Bow.cpp -o World\ Objects/Bow.o $(CXXFLAGS)

World\ Objects/ChestStructure.o: World\ Objects/ChestStructure.cpp
	$(CPP) -c World\ Objects/ChestStructure.cpp -o World\ Objects/ChestStructure.o $(CXXFLAGS)

World\ Objects/Container.o: World\ Objects/Container.cpp
	$(CPP) -c World\ Objects/Container.cpp -o World\ Objects/Container.o $(CXXFLAGS)

World\ Objects/DestinyGem.o: World\ Objects/DestinyGem.cpp
	$(CPP) -c World\ Objects/DestinyGem.cpp -o World\ Objects/DestinyGem.o $(CXXFLAGS)

World\ Objects/Doors.o: World\ Objects/Doors.cpp
	$(CPP) -c World\ Objects/Doors.cpp -o World\ Objects/Doors.o $(CXXFLAGS)

World\ Objects/Food.o: World\ Objects/Food.cpp
	$(CPP) -c World\ Objects/Food.cpp -o World\ Objects/Food.o $(CXXFLAGS)

World\ Objects/GemOfLife.o: World\ Objects/GemOfLife.cpp
	$(CPP) -c World\ Objects/GemOfLife.cpp -o World\ Objects/GemOfLife.o $(CXXFLAGS)

World\ Objects/Gold.o: World\ Objects/Gold.cpp
	$(CPP) -c World\ Objects/Gold.cpp -o World\ Objects/Gold.o $(CXXFLAGS)

World\ Objects/IcySaber.o: World\ Objects/IcySaber.cpp
	$(CPP) -c World\ Objects/IcySaber.cpp -o World\ Objects/IcySaber.o $(CXXFLAGS)

World\ Objects/ItemAreaLink.o: World\ Objects/ItemAreaLink.cpp
	$(CPP) -c World\ Objects/ItemAreaLink.cpp -o World\ Objects/ItemAreaLink.o $(CXXFLAGS)

World\ Objects/ObjectStatsSetup.o: World\ Objects/ObjectStatsSetup.cpp
	$(CPP) -c World\ Objects/ObjectStatsSetup.cpp -o World\ Objects/ObjectStatsSetup.o $(CXXFLAGS)

World\ Objects/Potions.o: World\ Objects/Potions.cpp
	$(CPP) -c World\ Objects/Potions.cpp -o World\ Objects/Potions.o $(CXXFLAGS)

World\ Objects/Sign.o: World\ Objects/Sign.cpp
	$(CPP) -c World\ Objects/Sign.cpp -o World\ Objects/Sign.o $(CXXFLAGS)

World\ Objects/SpellBook.o: World\ Objects/SpellBook.cpp
	$(CPP) -c World\ Objects/SpellBook.cpp -o World\ Objects/SpellBook.o $(CXXFLAGS)

World\ Objects/StandardObject.o: World\ Objects/StandardObject.cpp
	$(CPP) -c World\ Objects/StandardObject.cpp -o World\ Objects/StandardObject.o $(CXXFLAGS)

World\ Objects/Sword.o: World\ Objects/Sword.cpp
	$(CPP) -c World\ Objects/Sword.cpp -o World\ Objects/Sword.o $(CXXFLAGS)

World\ Objects/World\ Objects.o: World\ Objects/World\ Objects.cpp
	$(CPP) -c World\ Objects/World\ Objects.cpp -o World\ Objects/World\ Objects.o $(CXXFLAGS)
