#include "stdafx.h"
#include "MonsterStructure.h"

MonsterStructure::MonsterStructure()
: 
    cAttackLag( 0, 0 ),
    cStopLen( 0, 0 ), 
    wBaseReferenceID(0),
    level(0),
    appearance(0),
    Corpse(0),
    wUndead(0),
    AC(0),
    HP(0),
    DodgeSkill(0),    
    boCanAttack(TRUE),   
    block(1),
    boCanExitBuilding(FALSE),
    speed(0),   
    agressive(0),
    clan(0),    
    wLoXrange(25),
    wHiXrange(25),
    wLoYrange(25),
    wHiYrange(25),    
    XPperHit(0),
    XPperDeath(0),
    //nDeathGiveFlag(0),
    //nDeathFlagValue(0),
    //boDeathFlagIncrement(FALSE),    
    MinGold(0),
    MaxGold(0),   
    PhysicalAttackPercentage(0),   
    INT(0), 
    WIL(0), 
    STR(0), 
    AGI(0), 
    END(0), 
    LCK(100), 
    WIS(0),   
    AirResist(0), 
    WaterResist(0), 
    FireResist(0), 
    EarthResist(0), 
    LightResist(0), 
    DarkResist(0),
    AirPower(0),  
    WaterPower(0),  
    FirePower(0),  
    EarthPower(0),  
    LightPower(0),  
    DarkPower(0),    
    wBody(0), 
    wFeet(0), 
    wGloves(0), 
    wHelm(0), 
    wLegs(0), 
    wWeapon(0), 
    wShield(0), 
    wCape(0),    
    creature(0),
    behavior(0),
    groupmin(0),
    groupmax(0),    
    boPrivateTalk( FALSE ),    
    boInit( false )
{
    InitialPos.X = InitialPos.Y = InitialPos.world = -1;
}