// Here are *listed* ALL objects of the game! cool eh? *not*
#ifndef __STATICOBJECTREFERENCES_H
#define __STATICOBJECTREFERENCES_H

#define VARTYPE	//extern "C" const int IMPORT 

VARTYPE __OBJ_DECOR001;
VARTYPE __OBJ_DECOR002;
VARTYPE __OBJ_DECOR003;
VARTYPE __OBJ_DECOR004;
VARTYPE __OBJ_DECOR005;
VARTYPE __OBJ_DECOR006;
VARTYPE __OBJ_DECOR007;
VARTYPE __OBJ_DECOR008;
VARTYPE __OBJ_DECOR009;
VARTYPE __OBJ_DECOR010;
VARTYPE __OBJ_DECOR011;
VARTYPE __OBJ_DECOR012;
VARTYPE __OBJ_DECOR013;
VARTYPE __OBJ_DECOR014;
VARTYPE __OBJ_DECOR015;
VARTYPE __OBJ_DECOR016;
VARTYPE __OBJ_DECOR017;
VARTYPE __OBJ_DECOR018;

// standard objects
VARTYPE __OBJ_CAMP_FIRE;
VARTYPE __OBJ_WOODEN_CHAIR;
VARTYPE __OBJ_WOODEN_ROUND_CHAIR;
VARTYPE __OBJ_WOODEN_CHAIR_2;
VARTYPE __OBJ_WOODEN_ROUND_CHAIR_2;
VARTYPE __OBJ_WOODEN_CHAIR_FLIP;
VARTYPE __OBJ_WOODEN_CHAIR_2_FLIP;
VARTYPE __OBJ_WOODEN_ROUND_CHAIR_2_FLIP;
VARTYPE __OBJ_WOODEN_CHAIR_REV;
VARTYPE __OBJ_WOODEN_CHAIR_2_REV;
VARTYPE __OBJ_WOODEN_ROUND_CHAIR_2_REV;
VARTYPE __OBJ_WOODEN_CHAIR_I_REV;
VARTYPE __OBJ_WOODEN_CHAIR_2_I_REV;
VARTYPE __OBJ_WOODEN_ROUND_CHAIR_2_I_REV;

VARTYPE __OBJ_EMPTY_MUG;
VARTYPE __OBJ_BEER_MUG;
VARTYPE __OBJ_BEER_MUG_TOO_FULL;
VARTYPE __OBJ_EMPTY_GLASS;
VARTYPE __OBJ_BEVERAGE;
VARTYPE __OBJ_CUP_FULL;
VARTYPE __OBJ_WOODEN_CUP;
VARTYPE __OBJ_WOODEN_BOWL;
VARTYPE __OBJ_WOODEN_VASE;
VARTYPE __OBJ_KITCHEN_BOWL;
VARTYPE __OBJ_KITCHEN_SPOON;
VARTYPE __OBJ_KITCHEN_FORK;
VARTYPE __OBJ_KITCHEN_KNIFE;
VARTYPE __OBJ_ROULEAU_A_PATE;
VARTYPE __OBJ_BROOM_ON_WALL;
VARTYPE __OBJ_BROOM_ON_FLOOR;

VARTYPE __OBJ_BANJO;
VARTYPE __OBJ_TAMBOUR;
VARTYPE __OBJ_LONG_WHOOL_BALL;
VARTYPE __OBJ_WHOOL_BALL;
VARTYPE __OBJ_GREEN_WHOOL_BALL;
VARTYPE __OBJ_BLUE_WHOOL_BALL;
VARTYPE __OBJ_CHANDELLE;
VARTYPE __OBJ_CHANDELLE_SUR_PIED;
VARTYPE __OBJ_MIRROR;
VARTYPE __OBJ_PINCES;
VARTYPE __OBJ_BALANCE;
VARTYPE __OBJ_HOURGLASS;
VARTYPE __OBJ_EPROUVETTE_6_PACKS;
VARTYPE __OBJ_EPROUVETTE_3_PACKS;
VARTYPE __OBJ_EPROUVETTE_ALONE;
VARTYPE __OBJ_BUCHE_DE_BOIS;
VARTYPE __OBJ_LONGUE_VUE;
VARTYPE __OBJ_WOOD_PACK_CLASSED;
VARTYPE __OBJ_WOOD_PACK_MIXED;
VARTYPE __OBJ_FISHING_POLE;

// Quest Items
VARTYPE __OBJ_LETTER_FOR_MERCHANT;
VARTYPE __OBJ_FAKE_DRAGON_TOOTH;
VARTYPE __OBJ_DECAYED_BAT_WINGS;

// Food
VARTYPE __OBJ_JAMBON;
VARTYPE __OBJ_LONG_SAUSAGE;
VARTYPE __OBJ_SAUSAGE_PACK;
VARTYPE __OBJ_FAT_JAMBON;
VARTYPE __OBJ_CHICKEN;
VARTYPE __OBJ_BREAD;
VARTYPE __OBJ_PACK_OF_PASTRIES;
VARTYPE __OBJ_DEAD_FISHES;

// Potions
VARTYPE __OBJ_BLUE_POTION;
VARTYPE __OBJ_YELLOW_POTION;
VARTYPE __OBJ_BLACK_POTION;
VARTYPE __OBJ_PURPLE_POTION;


// Doors
VARTYPE __OBJ_WOODEN_DOOR;
VARTYPE __OBJ_WOODEN_DOOR_FLIP;

// Books
VARTYPE __OBJ_ROMANCE_BOOK;
VARTYPE __OBJ_LETTUCE;

VARTYPE __OBJ_GOLD;


#endif
