//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by T4C Editor.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_NPCEDITOR_DLG               101
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define IDD_T4CEDITOR_FORM              130
#define IDD_NAVIGATOR_DLG               131
#define IDI_NPC                         202
#define IDI_SEL_NPC                     203
#define IDD_QUERY_NPC_ID_DLG            204
#define IDR_NAVIGATOR                   207
#define IDR_NPC_EDITOR                  210
#define IDD_EDIT_KEYWORD                211
#define IDD_EDIT_CONDITION              212
#define IDD_EDIT_FOR                    213
#define IDD_EDIT_ASSIGNEMENT            214
#define IDD_EDIT_TEXT                   215
#define IDD_EDIT_COMMAND                216
#define IDI_INST_DEFAULT                217
#define IDI_INST_DEFAULT_SEL            218
#define IDI_INST_FOR                    219
#define IDI_INST_FOR_SEL                220
#define IDI_INST_KEYWORD                221
#define IDI_INST_KEYWORD_SEL            222
#define IDI_INST_COMMAND                223
#define IDI_INST_COMMAND_SEL            224
#define IDD_EDIT_MERCHANT               225
#define IDD_EDIT_TRAINER                226
#define IDC_INSTRUCTION_TREE            1000
#define IDC_CODE_TREE                   1001
#define IDC_NAME                        1002
#define ID_ADD_INSTRUCTION              1003
#define ID_ADD_KEYWORD                  1004
#define IDC_BINDED_CREATURE             1005
#define ID_DELETE_INSTRUCTION           1006
#define ID_EDIT_INSTRUCTION             1007
#define ID_MOVE_INSTRUCTION_UP          1008
#define ID_MOVE_INSTRUCTION_DOWN        1009
#define ID_SAVE_CHANGES                 1010
#define IDC_NPC_ID                      1011
#define ID_RENAME_NPC                   1012
#define IDC_NPC_TREE                    1013
#define IDC_QUERY_NPC_ID                1016
#define IDC_SAVE                        1017
#define IDC_NEW_KEYWORD                 1020
#define IDC_KEYWORD_LIST                1021
#define IDC_ADD                         1022
#define IDC_DELETE                      1023
#define IDC_AND_RELATION                1024
#define IDC_OR_RELATION                 1025
#define IDC_ORDERED_RELATION            1026
#define IDC_EXPRESSION                  1028
#define IDC_VERIFY_SYNTAX               1029
#define IDC_FOR_VAR                     1030
#define IDC_FOR_START                   1031
#define IDC_FOR_END                     1032
#define IDC_ASSIGN_VAR                  1034
#define IDC_ASSIGN_VALUE                1035
#define IDC_TEXT                        1036
#define IDC_PARAM1_TEXT                 1037
#define IDC_VAL1                        1039
#define IDC_PARAM2_TEXT                 1040
#define IDC_VAL2                        1041
#define IDC_VAL3                        1043
#define IDC_PARAM3_TEXT                 1044
#define IDC_EDIT_TRAINER                1045
#define IDC_EDIT_MERCHANT               1046
#define IDC_SOLD_ITEMS                  1048
#define IDC_BOUGHT_ITEMS                1049
#define IDC_ADD_SOLD                    1050
#define IDC_ITEMS                       1052
#define IDC_SOLD_PRICE                  1053
#define IDC_DELETE_SOLD                 1054
#define IDC_SELL_TYPES                  1055
#define IDC_MIN_PRICE                   1056
#define IDC_MAX_PRICE                   1057
#define IDC_ADD_BOUGHT                  1058
#define IDC_DELETE_BOUGHT               1059
#define IDC_ADD_TRAIN                   1061
#define IDC_DELETE_TRAIN                1062
#define IDC_ADD_TEACH                   1063
#define IDC_DELETE_TEACH                1064
#define IDC_TEACH_LIST                  1065
#define IDC_TRAIN_LIST                  1066
#define IDC_TAUGHT_SKILLS               1067
#define IDC_TRAINED_SKILLS              1068
#define IDC_MAX_POINTS                  1069
#define IDC_TRAIN_PRICE                 1070
#define IDC_TEACH_PRICE                 1071
#define ID_NPC_EDITOR                   32772
#define ID_VIEW_NAVIGATOR               32774
#define ID_NAV_RENAME                   32778
#define ID_RENAME                       32778
#define ID_NAV_ADD                      32781
#define ID_NAV_DELETE                   32782
#define ID_NAV_EDIT                     32783
#define ID_TILE_HORIZONTALLY            32784
#define ID_CASCADE                      32785
#define ID_TILE_VERTICALLY              32786
#define ID_EUH_DSFSDF                   32792
#define ID_CODE_EXPAND_TREE             32793
#define ID_WHATDOESITDO                 32794
#define ID_SAVEALL                      32796
#define ID_ADD                          32798
#define ID_DELETE                       32799
#define ID_EDIT                         32800
#define IDS_ERROR_NPC_ID_ALREADY_EXIST  61403
#define IDS_ERROR_NPC_ID_DOESNT_EXIST   61404
#define IDS_VALIDATE_TEXTERR            61405
#define IDS_VALIDATE_INTERR             61406
#define IDS_VALIDATE_FLOATERR           61407
#define IDS_VALIDATE_UNEXPECTEDERR      61408
#define IDS_NAVIGATOR_TITLE             61409
#define IDS_NPC_EDITOR_TITLE            61410
#define IDS_NO_NPC_SELECTED             61411
#define IDS_ERROR                       61412
#define IDS_ERROR_LOAD_NPC              61413
#define IDS_INST_GIVEITEM               61414
#define IDS_INST_GIVEITEM_HELP          61415
#define IDS_INST_GIVEXP                 61416
#define IDS_INST_GIVEXP_HELP            61417
#define IDS_INST_SETFLAG                61418
#define IDS_INST_SETFLAG_HELP           61419
#define IDS_INST_HEALPLAYER             61420
#define IDS_INST_HEALPLAYER_HELP        61421
#define IDS_INST_SAYTEXT                61422
#define IDS_INST_SAYTEXT_HELP           61423
#define IDS_INST_BREAKCONVERSATION      61424
#define IDS_INST_BREAKCONVERSATION_HELP 61425
#define IDS_INST_FIGHTPLAYER            61426
#define IDS_INST_FIGHTPLAYER_HELP       61427
#define IDS_INST_TAKEITEM               61428
#define IDS_INST_TAKEITEM_HELP          61429
#define IDS_INST_TELEPORT               61430
#define IDS_INST_TELEPORT_HELP          61431
#define IDS_INST_CASTSPELL              61432
#define IDS_INST_CASTSPELL_HELP         61433
#define IDS_INST_CASTSPELLSELF          61434
#define IDS_INST_CASTSPELLSELF_HELP     61435
#define IDS_INST_GIVEGOLD               61436
#define IDS_INST_GIVEGOLD_HELP          61437
#define IDS_INST_TAKEGOLD               61438
#define IDS_INST_TAKEGOLD_HELP          61439
#define IDS_INST_IF                     61440
#define IDS_INST_IF_HELP                61441
#define IDS_INST_ELSE                   61442
#define IDS_INST_ELSE_HELP              61443
#define IDS_INST_ELSEIF                 61444
#define IDS_INST_ELSEIF_HELP            61445
#define IDS_INST_FOR                    61446
#define IDS_INST_FOR_HELP               61447
#define IDS_INST_WHILE                  61448
#define IDS_INST_WHILE_HELP             61449
#define IDS_INST_KEYWORD                61450
#define IDS_INST_KEYWORD_HELP           61451
#define IDS_INITIAL_KEYWORD_NAME        61452
#define IDS_INITIAL_KEYWORD_HELP        61453
#define IDS_DEFAULT_KEYWORD_NAME        61454
#define IDS_DEFAULT_KEYWORD_HELP        61455
#define IDS_PROGRAM_ERROR               61456
#define IDS_CANNOT_ADD_SUBINSTRUCTION   61457
#define IDS_CANNOT_ADD_NON_KEYWORD_TO_ROOT 61458
#define IDS_CONFIRM_NPC_DELETION        61460
#define IDS_WARNING                     61461
#define IDS_CANNOT_LOAD_DB              61462
#define IDS_MUST_SELECT_COMBO_VALUE     61463
#define IDS_NEW_KEYWORD                 61464
#define IDS_NO_INST_SELECTED            61465
#define IDS_CONFIRM_INST_DELETION       61466
#define IDS_NO_PARENT_INST_SELECTED     61467
#define IDS_ELSE_MUST_BE_IF_CHILD       61468
#define IDS_CAN_ONLY_HAVE_ONE_ELSE      61469
#define IDS_EXPAND_TREE_BRANCH          61470
#define IDS_EDIT                        61471
#define IDS_ADD                         61472
#define IDS_DELETE                      61473
#define IDS_CANNOT_DELETE_INITIAL_DEFAULT_KEYWORD 61474
#define IDS_SAVE_CHANGES                61475
#define IDS_NOTHING_TO_EDIT             61476
#define IDS_NO_MORE_THEN_FIVE_KEYWORDS  61477
#define IDS_INFO                        61478
#define IDS_BOOST_FORMULA_SYNTAX_OK     61479
#define IDS_BOOST_FORMULA_SYNTAX_WRONG  61480
#define IDS_NEED_VARIABLE               61481
#define IDS_NEED_END_VALUE              61482
#define IDS_NEED_START_VALUE            61483
#define IDS_NEED_VALUE                  61484
#define IDS_INST_ASSIGN                 61485
#define IDS_INST_ASSIGN_HELP            61486
#define IDS_ATTRIB_BOOST_FORMULA        61487
#define IDS_PARAM_GIVEITEM              61488
#define IDS_PARAM_GIVEXP                61489
#define IDS_PARAM_SETFLAG_FLAG          61490
#define IDS_PARAM_SETFLAG_VALUE         61491
#define IDS_PARAM_HEALPLAYER            61492
#define IDS_PARAM_TAKEITEM              61493
#define IDS_PARAM_TELEPORT_X            61494
#define IDS_PARAM_TELEPORT_Y            61495
#define IDS_PARAM_TELEPORT_WORLD        61496
#define IDS_PARAM_CASTSPELL             61497
#define IDS_PARAM_GIVEGOLD              61498
#define IDS_PARAM_TAKEGOLD              61499
#define IDS_NEED_SELECTION              61500
#define IDS_RENAME                      61501
#define IDS_SELL_ARMOR                  61502
#define IDS_SELL_JEWEL                  61503
#define IDS_SELL_JEWEL_ARMOR            61504
#define IDS_SELL_WEAPON                 61505
#define IDS_SELL_JEWEL_WEAPON           61506
#define IDS_SELL_JUNK                   61507
#define IDS_SELL_POTION                 61508
#define IDS_SELL_PAWNSHOP               61509
#define IDS_SELL_MAGIC_ARMOR            61510
#define IDS_SELL_MAGIC_ITEM             61511
#define IDS_SELL_MAGIC_JEWEL            61512
#define IDS_SELL_MAGIC_JEWEL_ARMOR      61513
#define IDS_SELL_MAGIC_JEWEL_WEAPON     61514
#define IDS_SELL_MAGIC_POTION           61515
#define IDS_SELL_MAGIC_WEAPON           61516
#define IDS_INST_SENDSOLDITEMLIST       61517
#define IDS_INST_SENDSOLDITEMLIST_HELP  61518
#define IDS_INST_SENDBOUGHTITEMLIST     61519
#define IDS_INST_SENDBOUGHTITEMLIST_HELP 61520
#define IDS_WHATDOESITDO                61521
#define IDS_SKILL_STUN_BLOW             61522
#define IDS_SKILL_POWERFUL_BLOW         61523
#define IDS_SKILL_CRITICAL_STRIKE       61524
#define IDS_SKILL_FIRST_AID             61525
#define IDS_SKILL_PARRY                 61526
#define IDS_SKILL_MEDITATE              61527
#define IDS_SKILL_DODGE                 61528
#define IDS_SKILL_ATTACK                61529
#define IDS_SKILL_HIDE                  61530
#define IDS_SKILL_ROB                   61531
#define IDS_SKILL_SNEAK                 61532
#define IDS_SKILL_SEARCH                61533
#define IDS_SKILL_PICKLOCK              61534
#define IDS_SKILL_ARMOR_PENETRATION     61535
#define IDS_SKILL_PEEK                  61536
#define IDS_SKILL_RAPID_HEALING         61537
#define IDS_SKILL_ARCHERY               61538
#define IDS_SKILL_TAG                   61539
#define IDS_INST_SENDTRAINSKILLLIST     61540
#define IDS_INST_SENDTRAINSKILLLIST_HELP 61541
#define IDS_INST_SENDTEACHSKILLLIST     61542
#define IDS_INST_SENDTEACHSKILLLIST_HELP 61543
#define IDS_MUST_CLOSE_ALL              61544
#define IDS_SAVE_NPC_CHANGES            61545
#define IDS_FOR_DISPLAY                 61546
#define IDS_INST_PRIVATESYSTEMMESSAGE    61547
#define IDS_INST_PRIVATESYSTEMMESSAGE_HELP 61548
#define IDS_INST_GLOBALSYSTEMMESSAGE    61549
#define IDS_INST_GLOBALSYSTEMMESSAGE_HELP 61550
#define IDS_INST_SHOUTMESSAGE    61551
#define IDS_INST_SHOUTMESSAGE_HELP 61552
#define IDS_INST_SETGLOBALFLAG    61553
#define IDS_INST_SETGLOBALFLAG_HELP 61554
#define IDS_PARAM_SETGLOBALFLAG_FLAG          61555
#define IDS_PARAM_SETGLOBALFLAG_VALUE         61556
#define IDS_INST_GIVEKARMA                    61557
#define IDS_INST_GIVEKARMA_HELP               61558
#define IDS_PARAM_GIVEKARMA			          61559
#define IDS_PARAM_SHOUTMESSAGE_CHAN			  61660
#define IDS_PARAM_SHOUTMESSAGE_TXT			  61661
#define IDS_BYE_KEYWORD_NAME            61943
#define IDS_BYE_KEYWORD_HELP            61949
#define IDS_ONATTACKED_KEYWORD_NAME     61950
#define IDS_ONATTACKED_KEYWORD_HELP     61951
#define IDS_ONATTACK_KEYWORD_NAME			61952
#define IDS_ONATTACK_KEYWORD_HELP			61953
#define IDS_ONDEATH_KEYWORD_HELP        61957
#define IDS_ONDEATH_KEYWORD_NAME        61958
#define IDS_INST_SETSTATS               61959
#define IDS_INST_SETSTATS_HELP          61960
#define IDS_PARAM_SETSTATS_STAT         61961
#define IDS_PARAM_SETSTATS_VALUE        61962

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
