/////////////////////////////////////////////////////////////////////////////
#pragma hdrstop
#include <NPCStructure.h>
#include <DLLCreatures.h>


NPCstructure::NPC EfnisienNPC;
NPCstructure::NPC OlinHaad1NPC;
NPCstructure::NPC HighPriestGuntharNPC;
NPCstructure::NPC GuildLeaderEthanNPC;
NPCstructure::NPC OlinHaadAssassinNPC;
NPCstructure::NPC OlinHaadEliteGuardNPC;
NPCstructure::NPC UrikNPC;
NPCstructure::NPC UrikThiefNPC;
NPCstructure::NPC GypsyNPC;
NPCstructure::NPC DoorNPC;
NPCstructure::NPC FlippedDoorNPC;
NPCstructure::NPC DeskNPC;
NPCstructure::NPC PaintingNPC;
NPCstructure::NPC BookshelfNPC;
NPCstructure::NPC BedNPC;
NPCstructure::NPC TableNPC;
NPCstructure::NPC MetalChestNPC;
NPCstructure::NPC WoodenChestNPC;
NPCstructure::NPC OlinHaadCommanderNPC;
NPCstructure::NPC PortalNPC; 
NPCstructure::NPC WellNPC; 
NPCstructure::NPC MOBOlinHaadGuard3NPC; 
NPCstructure::NPC MOBOlinHaadGuard4NPC; 
NPCstructure::NPC EvilDragonNPC;	// TEST
NPCstructure::NPC DragonOrbNPC;		// TEST

///////////////////////////////////////////////////////////////////////////////////////////
// EPISODE 2 NPCs
NPCstructure::NPC CrimsonscaleNPC;
NPCstructure::NPC FountainOfKnowledgeNPC;
NPCstructure::NPC GorlokBloodaxeNPC;
NPCstructure::NPC HighPriestGunthar2NPC;
NPCstructure::NPC TarnianNPC;
NPCstructure::NPC NamelessBardNPC;
NPCstructure::NPC TreeOfWisdomNPC;
NPCstructure::NPC NexusStoneNPC;
NPCstructure::NPC RibcageNPC;
NPCstructure::NPC VicarKervianNPC; 
NPCstructure::NPC VicarAsgothNPC; 
NPCstructure::NPC VicarRamielNPC; 
NPCstructure::NPC VicarVharmesNPC;

///////////////////////////////////////////////////////////////////////////////////////////
// EPISODE 3 NPCs
NPCstructure::NPC OlinHaad2NPC;
NPCstructure::NPC OlinHaad3NPC;
NPCstructure::NPC DraconisGuardianNPC;
NPCstructure::NPC GluriurlNPC;

///////////////////////////////////////////////////////////////////////////////////////////
// SIDE QUEST NPCs

NPCstructure::NPC WandererNPC; 
NPCstructure::NPC CarmanNPC;
NPCstructure::NPC CarmanSpawnerNPC;
NPCstructure::NPC WindhowlSentryNPC;
NPCstructure::NPC DoppelgangerNPC;
NPCstructure::NPC FilandriusNPC;
NPCstructure::NPC AnthorTheMadNPC;
NPCstructure::NPC JormungandNPC;
NPCstructure::NPC HarvesterOfLifeNPC;
NPCstructure::NPC SpellPortalNPC;
NPCstructure::NPC VincentSwiftbladeNPC; 
NPCstructure::NPC MordredNPC;
NPCstructure::NPC MOBObsidianConclaveKnightNPC; 
NPCstructure::NPC MOBMercenaryLieutenantNPC;
NPCstructure::NPC MOBMercenaryNPC;
NPCstructure::NPC MOBMercenaryLeaderNPC;

void CreateNPC( void );

INIT_MONSTER_STAT_SETUP

SET_MONSTER( GluriurlNPC ) 
MOB_NPC_APPEARANCE              ( DEMON )
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 150 )
MOB_HP                          ( 25400 )
MOB_DODGE_SKILL                 ( 610 )
MOB_AC                          ( 75 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 50000 )
MOB_STR                         ( 165 )
MOB_DEX                         ( 149 )
MOB_END                         ( 149 )
MOB_INT                         ( 195 )
MOB_WIS                         ( 149 )
MOB_WIL                         ( 149 )
MOB_LCK                         ( 45 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 200 )
MOB_WATER_RESIST      ( 200 )
MOB_AIR_RESIST        ( 200 )
MOB_EARTH_RESIST      ( 200 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 200 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 1210 )
MOB_ATTACK_DMG_ROLL   (	"1d258+202" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_CREATE_SPELL_ATTACK( 0, 30 )
MOB_ATTACK_SPELL( 10708 )
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 0, 30 )
MOB_ATTACK_SPELL( 10709 )
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 0, 30 )
MOB_ATTACK_SPELL( 10710 )
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 0, 30 )
MOB_ATTACK_SPELL( 10618 )
MOB_ATTACK_PERCENTAGE( 25 )

SET_MONSTER				( OlinHaad3NPC )
MOB_NPC_APPEARANCE		( PUPPET ) 
MOB_AGRESSIVNESS		( -100 )
MOB_CLAN				( JARKO )
MOB_LEVEL				( 100 )
MOB_HP					( 1000000 )
MOB_DODGE_SKILL			( 1 )
MOB_AC					( 10000 )
MOB_XP_PER_HIT			( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 200 )
MOB_DEX                         ( 240 )
MOB_END                         ( 220 )
MOB_INT                         ( 200 )
MOB_WIS                         ( 210 )
MOB_WIL                         ( 250 )
MOB_LCK                         ( 220 )               

MOB_FIRE_POWER        ( 150 )
MOB_WATER_POWER       ( 150 )
MOB_AIR_POWER         ( 150 )
MOB_EARTH_POWER       ( 150 )
MOB_LIGHT_POWER       ( 150 )
MOB_DARK_POWER        ( 150 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5666 )
MOB_DARK_RESIST       ( 5000 )

MOB_CREATE_SPELL_ATTACK( 0, 20 )
MOB_ATTACK_SPELL( 10708 )
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 0, 20 )
MOB_ATTACK_SPELL( 10709 )
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 0, 20 )
MOB_ATTACK_SPELL( 10710 )
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 0, 20 )
MOB_ATTACK_SPELL( 10618 )
MOB_ATTACK_PERCENTAGE( 25 )

MOB_CREATE_PHYSICAL_ATTACK
MOB_ATTACK_SKILL      ( 730 )
MOB_ATTACK_DMG_ROLL   (	"1d90+69" )
MOB_ATTACK_PERCENTAGE ( 100 )
// MINdam: 70  MAXdam: 159  Average: 114.5 

MOB_DRESS_BODY ( NECROMANROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_WEAPON ( STAFF4 ) 

SET_MONSTER( MOBMercenaryLeaderNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 15 )
MOB_HP                          ( 450 )
MOB_DODGE_SKILL                 ( 70 )
MOB_AC                          ( 10 )
MOB_XP_PER_HIT                  ( 2.57 )
MOB_XP_DEATH                    ( 302.13 )
MOB_STR                         ( 30 )
MOB_DEX                         ( 28 )
MOB_END                         ( 28 )
MOB_INT                         ( 33 )
MOB_WIS                         ( 28 )
MOB_WIL                         ( 28 )
MOB_LCK                         ( 17 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 86 )
MOB_WATER_RESIST      ( 86 )
MOB_AIR_RESIST        ( 86 )
MOB_EARTH_RESIST      ( 86 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 57 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 190 )
MOB_ATTACK_DMG_ROLL   (	"1d120+12" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_BODY ( CHAIN_BODY )
MOB_DRESS_FEET ( PLATE_BOOT )
MOB_DRESS_GLOVES ( LEATHER_GLOVE) 
MOB_DRESS_HELM ( SKELETON_HELM )
MOB_DRESS_LEGS ( CHAIN_LEGS )
MOB_DRESS_WEAPON ( SKELETON_AXE )
MOB_DRESS_SHIELD ( SKELETON_SHIELD )
MOB_DRESS_CAPE ( REDCAPE )

MOB_ITEM( __OBJ_CRITICAL_HEALING_POTION, 1) 
MOB_ITEM( __OBJ_TORCH, 1) 

SET_MONSTER( MOBMercenaryLieutenantNPC ) 
MOB_NPC_APPEARANCE        ( PLAYER_SWORDMAN )
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 9 )
MOB_HP                          ( 300 )
MOB_DODGE_SKILL                 ( 42 )
MOB_AC                          ( 4 )
MOB_XP_PER_HIT                  ( 2 )
MOB_XP_DEATH                    ( 157 )
MOB_MIN_GOLD					( 12 )
MOB_MAX_GOLD					( 38 )
MOB_STR                         ( 23 )
MOB_DEX                         ( 22 )
MOB_END                         ( 22 )
MOB_INT                         ( 24 )
MOB_WIS                         ( 22 )
MOB_WIL                         ( 22 )
MOB_LCK                         ( 16 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 90 )
MOB_WATER_RESIST      ( 90 )
MOB_AIR_RESIST        ( 90 )
MOB_EARTH_RESIST      ( 90 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 60 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 118 )
MOB_ATTACK_DMG_ROLL   (	"1d11+7" )
MOB_ATTACK_PERCENTAGE   ( 100 )


SET_MONSTER( MOBMercenaryNPC ) 
MOB_NPC_APPEARANCE				( PLAYER_THIEF )
MOB_AGRESSIVNESS                ( 50 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 7 )
MOB_HP                          ( 116 )
MOB_DODGE_SKILL                 ( 43 )
MOB_AC                          ( 2 )
MOB_XP_PER_HIT                  ( 1.94 )
MOB_XP_DEATH                    ( 112.77 )
MOB_MIN_GOLD					( 12 )
MOB_MAX_GOLD					( 38 )
MOB_STR                         ( 21 )
MOB_DEX                         ( 21 )
MOB_END                         ( 21 )
MOB_INT                         ( 23 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 21 )
MOB_LCK                         ( 21 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 90 )
MOB_WATER_RESIST      ( 90 )
MOB_AIR_RESIST        ( 90 )
MOB_EARTH_RESIST      ( 90 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 60 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 94 )
MOB_ATTACK_DMG_ROLL   (	"1d10+5" )
MOB_ATTACK_PERCENTAGE   ( 100 )

SET_MONSTER( MOBOlinHaadGuard3NPC ) 
MOB_APPEARANCE					( BRIGAND )
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( LIGHTHAVEN )
MOB_LEVEL                       ( 3 )
MOB_HP                          ( 55 )
MOB_DODGE_SKILL                 ( 22 )
MOB_AC                          ( 1 )
MOB_XP_PER_HIT                  ( 1.6756 )
MOB_XP_DEATH                    ( 46.0778 )
MOB_MIN_GOLD					( 5 )
MOB_MAX_GOLD					( 16 )
MOB_STR                         ( 18 )
MOB_DEX                         ( 17 )
MOB_END                         ( 17 )
MOB_INT                         ( 18 )
MOB_WIS                         ( 17 )
MOB_WIL                         ( 15 )
MOB_LCK                         ( 15 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 92 )
MOB_WATER_RESIST      ( 92 )
MOB_AIR_RESIST        ( 92 )
MOB_EARTH_RESIST      ( 92 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 61 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 46 )
MOB_ATTACK_DMG_ROLL   (	"1d5+3" )
MOB_ATTACK_PERCENTAGE   ( 100 )

SET_MONSTER( MOBOlinHaadGuard4NPC ) 
MOB_APPEARANCE					( BRIGAND )
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( LIGHTHAVEN )
MOB_LEVEL                       ( 4 )
MOB_HP                          ( 69 )
MOB_DODGE_SKILL                 ( 26 )
MOB_AC                          ( 2 )
MOB_XP_PER_HIT                  ( 1.7359 )
MOB_XP_DEATH                    ( 59.8889 )
MOB_MIN_GOLD					( 7 )
MOB_MAX_GOLD					( 22 )
MOB_STR                         ( 19 )
MOB_DEX                         ( 18 )
MOB_END                         ( 18 )
MOB_INT                         ( 19 )
MOB_WIS                         ( 18 )
MOB_WIL                         ( 15 )
MOB_LCK                         ( 15 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 92 )
MOB_WATER_RESIST      ( 92 )
MOB_AIR_RESIST        ( 92 )
MOB_EARTH_RESIST      ( 92 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 61 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 46 )
MOB_ATTACK_DMG_ROLL   (	"1d7+3" )
MOB_ATTACK_PERCENTAGE   ( 100 )

SET_MONSTER( VincentSwiftbladeNPC ) 
MOB_NPC_APPEARANCE	( PUPPET ) 
MOB_AGRESSIVNESS	( -100 )
MOB_CLAN			( LIGHTHAVEN )
MOB_LEVEL			( 60 )
MOB_HP				( 1000000 )
MOB_DODGE_SKILL		( 65535 )
MOB_AC				( 100000 )
MOB_XP_PER_HIT		( 0 )
MOB_XP_DEATH		( 0 )
MOB_STR				( 20 )
MOB_DEX				( 24 )
MOB_END				( 22 )
MOB_INT				( 20 )
MOB_WIS				( 21 )
MOB_WIL				( 25 )
MOB_LCK				( 22 )               

MOB_FIRE_POWER		( 100 )
MOB_WATER_POWER		( 100 )
MOB_AIR_POWER		( 100 )
MOB_EARTH_POWER		( 100 )
MOB_LIGHT_POWER		( 100 )
MOB_DARK_POWER		( 100 )

MOB_FIRE_RESIST		( 5000 )
MOB_WATER_RESIST	( 5000 )
MOB_AIR_RESIST		( 5000 )
MOB_EARTH_RESIST	( 5000 )
MOB_LIGHT_RESIST	( 5000 )
MOB_DARK_RESIST		( 5000 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 730 )
MOB_ATTACK_DMG_ROLL   (	"1d90+69" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_BODY ( STUDDEDARMOR )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_LEGS ( LEATHER_PANTS )

SET_MONSTER           ( MordredNPC )
MOB_NPC_APPEARANCE    ( PUPPET ) 
MOB_AGRESSIVNESS      ( 100 ) 
MOB_CLAN              ( JARKO )
MOB_HP                ( 2301 )
MOB_DODGE_SKILL       ( 330 )
MOB_AC                ( 40 )
MOB_LEVEL             ( 80 )
MOB_XP_PER_HIT        ( 8.18 )
MOB_XP_DEATH          ( 9409.00 )
MOB_MIN_GOLD          ( 143 )
MOB_MAX_GOLD          ( 440 )
MOB_STR               ( 95 )
MOB_DEX               ( 86 )
MOB_END               ( 86 )
MOB_INT               ( 111 )
MOB_WIS               ( 86 )
MOB_WIL               ( 86 )
MOB_LCK               ( 31 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 56 )
MOB_WATER_RESIST      ( 56 )
MOB_AIR_RESIST        ( 56 )
MOB_EARTH_RESIST      ( 56 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 56 )

MOB_CREATE_PHYSICAL_ATTACK
MOB_ATTACK_SKILL      ( 970 )
MOB_ATTACK_DMG_ROLL   ( "1d138+107" )
MOB_ATTACK_PERCENTAGE ( 100 )
// MINdam: 108  MAXdam: 245  Average: 176.5 

MOB_DRESS_BODY ( NECROMANROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_LEGS ( LEATHER_PANTS )
MOB_DRESS_WEAPON ( REAL_DARKSWORD ) 

MOB_ITEM( __OBJ_RAW_CRYSTAL, 5)
MOB_ITEM( __OBJ_CRITICAL_HEALING_POTION, 1) 
MOB_ITEM( __OBJ_ROUGH_AMETHYST, 2 ) 
MOB_ITEM( __OBJ_ROUGH_SAPPHIRE, 0.4 ) 
MOB_ITEM( __OBJ_ROUGH_AQUAMARINE, 0.1 ) 
MOB_ITEM( __OBJ_PLATE_BOOTS, 0.5) 
MOB_ITEM( __OBJ_PLATE_GAUNTLETS, 0.25) 
MOB_ITEM( __OBJ_PLATE_HELMET, 0.25 ) 
MOB_ITEM( __OBJ_PLATE_LEGGINGS, 0.2) 
MOB_ITEM( __OBJ_PLATEMAIL, 0.1) 
MOB_ITEM( __OBJ_PLATE_PROTECTOR, 0.25 ) 
MOB_ITEM( __OBJ_DARKWOOD_SHIELD, 0.25)  

SET_MONSTER           ( MOBObsidianConclaveKnightNPC )
MOB_AGRESSIVNESS      ( 100 ) 
MOB_NPC_APPEARANCE        ( PLAYER_SWORDMAN )
MOB_CLAN              ( JARKO )
MOB_HP                ( 1801 )   
MOB_DODGE_SKILL       ( 282 )
MOB_AC                ( 34 )
MOB_LEVEL             ( 68 )
MOB_XP_PER_HIT        ( 7.07 )
MOB_XP_DEATH          ( 6369.13 )
MOB_MIN_GOLD          ( 122 )
MOB_MAX_GOLD          ( 374 )
MOB_STR               ( 83 )
MOB_DEX               ( 76 )
MOB_END               ( 76 )
MOB_INT               ( 96 )
MOB_WIS               ( 76 )
MOB_WIL               ( 76 )
MOB_LCK               ( 28 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 75 )
MOB_WATER_RESIST      ( 75 )
MOB_AIR_RESIST        ( 75 )
MOB_EARTH_RESIST      ( 75 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 75 )

MOB_CREATE_PHYSICAL_ATTACK
MOB_ATTACK_SKILL      ( 826 )
MOB_ATTACK_DMG_ROLL   ( "1d106+81" )
MOB_ATTACK_PERCENTAGE ( 100 )
// MINdam: 82  MAXdam: 187  Average: 134.5 

MOB_ITEM( __OBJ_CRITICAL_HEALING_POTION, 1) 
MOB_ITEM( __OBJ_PLATE_BOOTS, 0.25) 
MOB_ITEM( __OBJ_PLATE_GAUNTLETS, 0.25) 
MOB_ITEM( __OBJ_PLATE_LEGGINGS, 0.2) 
MOB_ITEM( __OBJ_PLATEMAIL, 0.1) 
MOB_ITEM( __OBJ_PLATE_PROTECTOR, 0.25 ) 

SET_MONSTER( VicarVharmesNPC ) 
MOB_APPEARANCE        ( SKELETON_KING )
MOB_AGRESSIVNESS      ( 100 )
MOB_CLAN              ( JARKO )
MOB_LEVEL             ( 60 )
MOB_HP                ( 1497 )
MOB_DODGE_SKILL       ( 250 )
MOB_AC                ( 30 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 14599.5 )
MOB_MIN_GOLD          ( 107 )
MOB_MAX_GOLD          ( 330 )
MOB_STR               ( 75 )
MOB_DEX               ( 68 )
MOB_END               ( 68 )
MOB_INT               ( 87 )
MOB_WIS               ( 68 )
MOB_WIL               ( 100 )
MOB_LCK               ( 34 )

MOB_FIRE_POWER        ( 150 )
MOB_WATER_POWER       ( 150 )
MOB_AIR_POWER         ( 150 )
MOB_EARTH_POWER       ( 150 )
MOB_LIGHT_POWER       ( 150 )
MOB_DARK_POWER        ( 150 )

MOB_FIRE_RESIST       ( 87 )
MOB_WATER_RESIST      ( 87 )
MOB_AIR_RESIST        ( 87 )
MOB_EARTH_RESIST      ( 87 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 87 )

MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10086 )       // ice shard
MOB_ATTACK_PERCENTAGE( 33 )
MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10096 )       // fire bolt
MOB_ATTACK_PERCENTAGE( 33 )
MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10095 )       // fireball
MOB_ATTACK_PERCENTAGE( 34 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10119 )       // drain life
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10096 )       // fire bolt
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10120 )       // lightning bolt
MOB_ATTACK_PERCENTAGE( 45 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10122 )       // heal serious
MOB_ATTACK_PERCENTAGE( 5 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10094 )       // stone shard
MOB_ATTACK_PERCENTAGE( 50 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10095 )       // fireball
MOB_ATTACK_PERCENTAGE( 45 )

MOB_CREATE_PHYSICAL_ATTACK
MOB_ATTACK_SKILL      ( 1150 )
MOB_ATTACK_DMG_ROLL   (	"1d114+87" )
MOB_ATTACK_PERCENTAGE ( 100 )
// MINdam: 128  MAXdam: 291

MOB_ITEM( __OBJ_ARMBAND_OF_VIGOR, 1) 

SET_MONSTER( VicarRamielNPC )
MOB_APPEARANCE        ( SKELETON_KING )
MOB_AGRESSIVNESS      ( 100 )
MOB_CLAN              ( JARKO )
MOB_LEVEL             ( 60 )
MOB_HP                ( 1497 )
MOB_DODGE_SKILL       ( 250 )
MOB_AC                ( 30 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 14599.5 )
MOB_MIN_GOLD          ( 107 )
MOB_MAX_GOLD          ( 330 )
MOB_STR               ( 75 )
MOB_DEX               ( 68 )
MOB_END               ( 68 )
MOB_INT               ( 87 )
MOB_WIS               ( 68 )
MOB_WIL               ( 100 )
MOB_LCK               ( 34 )

MOB_FIRE_POWER        ( 150 )
MOB_WATER_POWER       ( 150 )
MOB_AIR_POWER         ( 150 )
MOB_EARTH_POWER       ( 150 )
MOB_LIGHT_POWER       ( 150 )
MOB_DARK_POWER        ( 150 )

MOB_FIRE_RESIST       ( 87 )
MOB_WATER_RESIST      ( 87 )
MOB_AIR_RESIST        ( 87 )
MOB_EARTH_RESIST      ( 87 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 87 )

MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10086 )       // ice shard
MOB_ATTACK_PERCENTAGE( 33 )
MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10096 )       // fire bolt
MOB_ATTACK_PERCENTAGE( 33 )
MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10095 )       // fireball
MOB_ATTACK_PERCENTAGE( 34 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10119 )       // drain life
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10096 )       // fire bolt
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10120 )       // lightning bolt
MOB_ATTACK_PERCENTAGE( 45 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10122 )       // heal serious
MOB_ATTACK_PERCENTAGE( 5 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10094 )       // stone shard
MOB_ATTACK_PERCENTAGE( 50 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10095 )       // fireball
MOB_ATTACK_PERCENTAGE( 45 )

MOB_CREATE_PHYSICAL_ATTACK
MOB_ATTACK_SKILL      ( 1150 )
MOB_ATTACK_DMG_ROLL   (	"1d114+87" )
MOB_ATTACK_PERCENTAGE ( 100 )
// MINdam: 128  MAXdam: 291

MOB_ITEM( __OBJ_GIRDLE_OF_INSIGHT, 1) 


SET_MONSTER( VicarAsgothNPC )  
MOB_APPEARANCE        ( SKELETON_KING )
MOB_AGRESSIVNESS      ( 100 )
MOB_CLAN              ( JARKO )
MOB_LEVEL             ( 60 )
MOB_HP                ( 1497 )
MOB_DODGE_SKILL       ( 250 )
MOB_AC                ( 30 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 14599.5 )
MOB_MIN_GOLD          ( 107 )
MOB_MAX_GOLD          ( 330 )
MOB_STR               ( 75 )
MOB_DEX               ( 68 )
MOB_END               ( 68 )
MOB_INT               ( 87 )
MOB_WIS               ( 68 )
MOB_WIL               ( 100 )
MOB_LCK               ( 34 )

MOB_FIRE_POWER        ( 200 )
MOB_WATER_POWER       ( 150 )
MOB_AIR_POWER         ( 150 )
MOB_EARTH_POWER       ( 150 )
MOB_LIGHT_POWER       ( 150 )
MOB_DARK_POWER        ( 150 )

MOB_FIRE_RESIST       ( 100 )
MOB_WATER_RESIST      ( 87 )
MOB_AIR_RESIST        ( 87 )
MOB_EARTH_RESIST      ( 87 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 87 )

MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10086 )       // ice shard
MOB_ATTACK_PERCENTAGE( 33 )
MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10096 )       // fire bolt
MOB_ATTACK_PERCENTAGE( 33 )
MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10095 )       // fireball
MOB_ATTACK_PERCENTAGE( 34 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10119 )       // drain life
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10096 )       // fire bolt
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10120 )       // lightning bolt
MOB_ATTACK_PERCENTAGE( 45 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10122 )       // heal serious
MOB_ATTACK_PERCENTAGE( 5 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10094 )       // stone shard
MOB_ATTACK_PERCENTAGE( 50 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10095 )       // fireball
MOB_ATTACK_PERCENTAGE( 45 )

MOB_CREATE_PHYSICAL_ATTACK
MOB_ATTACK_SKILL      ( 1150 )
MOB_ATTACK_DMG_ROLL   (	"1d114+87" )
MOB_ATTACK_PERCENTAGE ( 100 )
// MINdam: 128  MAXdam: 291

MOB_ITEM( __OBJ_ARMBAND_OF_VIGOR, 1) 

SET_MONSTER( VicarKervianNPC )
MOB_APPEARANCE        ( SKELETON_KING )
MOB_AGRESSIVNESS      ( 100 )
MOB_CLAN              ( JARKO )
MOB_LEVEL             ( 60 )
MOB_HP                ( 1497 )
MOB_DODGE_SKILL       ( 250 )
MOB_AC                ( 30 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 14599.5 )
MOB_MIN_GOLD          ( 107 )
MOB_MAX_GOLD          ( 330 )
MOB_STR               ( 75 )
MOB_DEX               ( 68 )
MOB_END               ( 68 )
MOB_INT               ( 87 )
MOB_WIS               ( 68 )
MOB_WIL               ( 100 )
MOB_LCK               ( 34 )

MOB_FIRE_POWER        ( 150 )
MOB_WATER_POWER       ( 150 )
MOB_AIR_POWER         ( 150 )
MOB_EARTH_POWER       ( 150 )
MOB_LIGHT_POWER       ( 150 )
MOB_DARK_POWER        ( 150 )

MOB_FIRE_RESIST       ( 87 )
MOB_WATER_RESIST      ( 87 )
MOB_AIR_RESIST        ( 87 )
MOB_EARTH_RESIST      ( 87 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 87 )

MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10096 )       // fire bolt
MOB_ATTACK_PERCENTAGE( 50 )
MOB_CREATE_SPELL_ATTACK( 12, 18 )
MOB_ATTACK_SPELL( 10095 )       // fireball
MOB_ATTACK_PERCENTAGE( 50 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10119 )       // drain life
MOB_ATTACK_PERCENTAGE( 50 )
MOB_CREATE_SPELL_ATTACK( 7, 11 )
MOB_ATTACK_SPELL( 10120 )       // lightning bolt
MOB_ATTACK_PERCENTAGE( 45 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10122 )       // heal serious
MOB_ATTACK_PERCENTAGE( 5 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10094 )       // stone shard
MOB_ATTACK_PERCENTAGE( 50 )
MOB_CREATE_SPELL_ATTACK( 2, 6 )
MOB_ATTACK_SPELL( 10095 )       // fireball
MOB_ATTACK_PERCENTAGE( 45 )
MOB_CREATE_PHYSICAL_ATTACK
MOB_ATTACK_SKILL      ( 1150 )
MOB_ATTACK_DMG_ROLL   (	"1d114+87" )
MOB_ATTACK_PERCENTAGE ( 100 )
// MINdam: 128  MAXdam: 291

MOB_ITEM( __OBJ_GIRDLE_OF_INSIGHT, 1) 

SET_MONSTER           ( WellNPC )
MOB_SPEED             ( 65, dice( 1, 1000, 500 ), 25, dice( 1, 500, 500 ) )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( WELL_TALK )
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER( PortalNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( PORTAL )
MOB_CLAN              ( PEACE ) 
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 100 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )


SET_MONSTER( EvilDragonNPC )      
MOB_AGRESSIVNESS      ( 100 ) 
MOB_APPEARANCE        ( KRAANIANTANK ) 
MOB_CLAN              ( JARKO ) 
MOB_HP                ( 10000 )
MOB_DODGE_SKILL       ( 10000 )
MOB_AC                ( 10000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 500 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 37 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 370 )
MOB_ATTACK_DMG_ROLL   (	"1d36+27" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_CREATE_SPELL_ATTACK( 1, 25 )
MOB_ATTACK_SPELL( 10096 )       


SET_MONSTER( WandererNPC ) 
MOB_NPC_APPEARANCE	( PUPPET )
MOB_AGRESSIVNESS	( -100 )
MOB_CLAN			( LIGHTHAVEN )
MOB_LEVEL			( 100 )
MOB_HP				( 1000000 )
MOB_DODGE_SKILL		( 65535 )
MOB_AC				( 1000000 )
MOB_XP_PER_HIT		( 0 )
MOB_XP_DEATH        ( 0 )
MOB_STR             ( 65 )
MOB_DEX             ( 63 )
MOB_END             ( 67 )
MOB_INT             ( 47 )
MOB_WIS             ( 87 )
MOB_WIL             ( 79 )
MOB_LCK             ( 54 )

MOB_FIRE_POWER		( 100 )
MOB_WATER_POWER		( 100 )
MOB_AIR_POWER		( 100 )
MOB_EARTH_POWER		( 100 )
MOB_LIGHT_POWER		( 100 )
MOB_DARK_POWER		( 100 )

MOB_FIRE_RESIST		( 5000 )
MOB_WATER_RESIST	( 5000 )
MOB_AIR_RESIST		( 5000 )
MOB_EARTH_RESIST	( 5000 )
MOB_LIGHT_RESIST	( 5000 )
MOB_DARK_RESIST		( 5000 )

MOB_CREATE_PHYSICAL_ATTACK
MOB_ATTACK_SKILL      ( 250 )
MOB_ATTACK_DMG_ROLL   (	"1d23+16" )
MOB_ATTACK_PERCENTAGE ( 100 )

MOB_DRESS_BODY ( ARMOREDROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_LEGS ( LEATHER_PANTS )
MOB_DRESS_WEAPON ( STAFF2 ) 

SET_MONSTER( DragonOrbNPC )      
MOB_AGRESSIVNESS      ( -100 ) 
MOB_APPEARANCE        ( RED_GOBLINBOSS ) 
MOB_CLAN			  ( PEACE ) 
MOB_HP                ( 10000 )
MOB_DODGE_SKILL       ( 0 )
MOB_AC                ( 10 )
MOB_LEVEL             ( 50 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 100 )
MOB_DEX               ( 100 )
MOB_END               ( 100 )
MOB_INT               ( 100 )
MOB_WIS               ( 100 )
MOB_WIL               ( 100 )
MOB_LCK               ( 100 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 100 )
MOB_WATER_RESIST      ( 100 )
MOB_AIR_RESIST        ( 100 )
MOB_EARTH_RESIST      ( 100 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 100 )
MOB_CAN_ATTACK	( FALSE ) 


SET_MONSTER( EfnisienNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( LIGHTHAVEN )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CAN_ATTACK       (FALSE)

MOB_DRESS_BODY ( CHAIN_BODY )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_LEGS ( LEATHER_PANTS )
MOB_DRESS_WEAPON ( STAFF2 ) 

SET_MONSTER( OlinHaad1NPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( PEACE )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 10000 )
MOB_ATTACK_DMG_ROLL   (	"(target.maxhp*15)/100+target.ac" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_BODY ( NECROMANROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_WEAPON ( STAFF4 ) 

SET_MONSTER( HighPriestGuntharNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( PEACE )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CAN_ATTACK       (FALSE)

MOB_DRESS_BODY ( WHITEROBE )
MOB_DRESS_FEET ( LEATHER_BOOTS )

SET_MONSTER( GuildLeaderEthanNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( PEACE )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CAN_ATTACK       (FALSE)

MOB_DRESS_BODY ( MAGEROBE )
MOB_DRESS_FEET ( LEATHER_BOOTS )

SET_MONSTER( OlinHaadAssassinNPC ) 
MOB_APPEARANCE					( BRIGAND )
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 1 )
MOB_HP                          ( 27 )
MOB_DODGE_SKILL                 ( 14 )
MOB_AC                          ( 0 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 16 )
MOB_DEX                         ( 15 )
MOB_END                         ( 15 )
MOB_INT                         ( 16 )
MOB_WIS                         ( 15 )
MOB_WIL                         ( 15 )
MOB_LCK                         ( 15 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 93 )
MOB_WATER_RESIST      ( 93 )
MOB_AIR_RESIST        ( 93 )
MOB_EARTH_RESIST      ( 93 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 62 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 30 )
MOB_ATTACK_DMG_ROLL   (	"if(target.hp>4?if(target.hp<15?target.hp-4:15-1d10):0)" )
MOB_ATTACK_PERCENTAGE   ( 100 )

SET_MONSTER( OlinHaadEliteGuardNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 10 )
MOB_HP                          ( 500000 )
MOB_DODGE_SKILL                 ( 50 )
MOB_AC                          ( 0 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 200 )
MOB_DEX                         ( 240 )
MOB_END                         ( 220 )
MOB_INT                         ( 200 )
MOB_WIS                         ( 210 )
MOB_WIL                         ( 250 )
MOB_LCK                         ( 220 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 10000 )
MOB_ATTACK_DMG_ROLL   (	"if(target.hp>5?if(target.hp<20?target.hp-5:20-1d5):0)" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_BODY ( CHAIN_BODY )
MOB_DRESS_FEET ( PLATE_BOOT )
MOB_DRESS_GLOVES ( LEATHER_GLOVE) 
MOB_DRESS_HELM ( CHAIN_COIF )
MOB_DRESS_LEGS ( CHAIN_LEGS )
MOB_DRESS_WEAPON ( AXE )
MOB_DRESS_SHIELD ( ROMAN_SHIELD )
MOB_DRESS_CAPE ( REDCAPE )

SET_MONSTER( UrikNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CAN_ATTACK       (FALSE)

MOB_DRESS_BODY ( LEATHER_ARMOR )
MOB_DRESS_FEET ( LEATHER_BOOTS )
MOB_DRESS_LEGS ( LEATHER_PANTS )

SET_MONSTER( UrikThiefNPC ) 
MOB_APPEARANCE					( BRIGAND )
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 8 )
MOB_HP                          ( 132 )
MOB_DODGE_SKILL                 ( 42 )
MOB_AC                          ( 4 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 23 )
MOB_DEX                         ( 22 )
MOB_END                         ( 22 )
MOB_INT                         ( 24 )
MOB_WIS                         ( 22 )
MOB_WIL                         ( 22 )
MOB_LCK                         ( 16 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 90 )
MOB_WATER_RESIST      ( 90 )
MOB_AIR_RESIST        ( 90 )
MOB_EARTH_RESIST      ( 90 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 60 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 106 )
MOB_ATTACK_DMG_ROLL   (	"1d11+6" )
MOB_ATTACK_PERCENTAGE   ( 100 )

SET_MONSTER( GypsyNPC ) 
MOB_NPC_APPEARANCE              ( FEMALE_PUPPET ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( PEACE )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 100 )
MOB_WATER_RESIST      ( 100 )
MOB_AIR_RESIST        ( 100 )
MOB_EARTH_RESIST      ( 100 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 100 )

MOB_CAN_ATTACK       (FALSE)

MOB_DRESS_BODY ( BODY_CLOTH1 )
MOB_DRESS_LEGS ( LEG_CLOTH1 )

SET_MONSTER           ( DoorNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( DOOR_TALK )
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( FlippedDoorNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( DOOR_TALK_I ) 
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( DeskNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( DOOR_TALK )	// GAMEDESIGN: Need desk appearance that can be clicked on
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( PaintingNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( DOOR_TALK )	// GAMEDESIGN: Need painting appearance that can be clicked on
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( BookshelfNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( DOOR_TALK )	// GAMEDESIGN: Need bookshelf appearance that can be clicked on
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( BedNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( DOOR_TALK )	// GAMEDESIGN: Need bed appearance that can be clicked on
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( TableNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( DOOR_TALK )	// GAMEDESIGN: Need table appearance that can be clicked on
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( MetalChestNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( CHEST_TALK ) // GAMEDESIGN: Need metal chest appearance that can be clicked on
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( WoodenChestNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( CHEST_TALK ) // GAMEDESIGN: Need wooden chest appearance that can be clicked on
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER( OlinHaadCommanderNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 15 )
MOB_HP                          ( 254 )
MOB_DODGE_SKILL                 ( 70 )
MOB_AC                          ( 7 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 30 )
MOB_DEX                         ( 28 )
MOB_END                         ( 28 )
MOB_INT                         ( 33 )
MOB_WIS                         ( 28 )
MOB_WIL                         ( 28 )
MOB_LCK                         ( 17 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 86 )
MOB_WATER_RESIST      ( 86 )
MOB_AIR_RESIST        ( 86 )
MOB_EARTH_RESIST      ( 86 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 57 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 190 )
MOB_ATTACK_DMG_ROLL   (	"1d17+12" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_BODY ( CHAIN_BODY )
MOB_DRESS_FEET ( PLATE_BOOT )
MOB_DRESS_GLOVES ( LEATHER_GLOVE) 
MOB_DRESS_HELM ( CHAIN_COIF )
MOB_DRESS_LEGS ( CHAIN_LEGS )
MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_SHIELD ( BAROSSA_SHIELD )
MOB_DRESS_CAPE ( REDCAPE )

SET_MONSTER( CrimsonscaleNPC )
MOB_NPC_APPEARANCE              ( DRAGON )  
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( PEACE )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 10000 )
MOB_LCK                         ( 22 )               
MOB_CAN_ATTACK                  (FALSE)

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

SET_MONSTER           ( FountainOfKnowledgeNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( WELL_TALK ) // GAMEDESIGN: Need fountain appearance that can be clicked on
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER( GorlokBloodaxeNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 25 )
MOB_HP                          ( 463 )
MOB_DODGE_SKILL                 ( 110 )
MOB_AC                          ( 12 )
MOB_XP_PER_HIT                  ( 3.5 )
MOB_XP_DEATH                    ( 810 )
MOB_STR                         ( 40 )
MOB_DEX                         ( 37 )
MOB_END                         ( 37 )
MOB_INT                         ( 45 )
MOB_WIS                         ( 37 )
MOB_WIL                         ( 37 )
MOB_LCK                         ( 20 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 82 )
MOB_WATER_RESIST      ( 82 )
MOB_AIR_RESIST        ( 82 )
MOB_EARTH_RESIST      ( 82 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 54 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 310 )
MOB_ATTACK_DMG_ROLL   (	"1d29+21" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_BODY ( CHAIN_BODY )
MOB_DRESS_FEET ( PLATE_BOOT )
MOB_DRESS_GLOVES ( LEATHER_GLOVE) 
MOB_DRESS_HELM ( CHAIN_COIF )
MOB_DRESS_LEGS ( CHAIN_LEGS )
MOB_DRESS_WEAPON ( AXE )
MOB_DRESS_SHIELD ( ROMAN_SHIELD )
MOB_DRESS_CAPE ( REDCAPE )

SET_MONSTER( HighPriestGunthar2NPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( PEACE )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 50000 )
MOB_AC                          ( 0 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CAN_ATTACK       (FALSE)

MOB_DRESS_BODY ( WHITEROBE )
MOB_DRESS_FEET ( LEATHER_BOOTS )

SET_MONSTER( TarnianNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( LIGHTHAVEN )
MOB_LEVEL                       ( 60 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 250 )
MOB_AC                          ( 100000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 730 )
MOB_ATTACK_DMG_ROLL   (	"1d90+69" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_BODY ( LEATHER_ARMOR )
MOB_DRESS_FEET ( LEATHER_BOOTS )
MOB_DRESS_LEGS ( LEATHER_PANTS )
MOB_DRESS_CAPE ( REDCAPE )

SET_MONSTER( NamelessBardNPC ) 
MOB_APPEARANCE                  ( ATROCITY ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( PEACE )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CAN_ATTACK       (FALSE)

SET_MONSTER           ( TreeOfWisdomNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_APPEARANCE		  ( TREE_ENT )
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( NexusStoneNPC )
MOB_SPEED             ( 65, dice( 1, 1000, 500 ), 25, dice( 1, 500, 500 ) )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( SUNDIAL_TALK )
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER           ( RibcageNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( RIB_TALK ) 
// MOB_OBJ_APPEARANCE    ( CHEST_TALK )
MOB_CLAN              ( PEACE )
MOB_HP                ( 1000000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000000 )
MOB_LEVEL             ( 200 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

SET_MONSTER( OlinHaad2NPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 100000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 200 )
MOB_DEX                         ( 240 )
MOB_END                         ( 220 )
MOB_INT                         ( 200 )
MOB_WIS                         ( 210 )
MOB_WIL                         ( 250 )
MOB_LCK                         ( 220 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 100 )
MOB_WATER_RESIST      ( 100 )
MOB_AIR_RESIST        ( 100 )
MOB_EARTH_RESIST      ( 100 )
MOB_LIGHT_RESIST      ( 100 )
MOB_DARK_RESIST       ( 100 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 10000 )
MOB_ATTACK_DMG_ROLL   (	"if(target.hp>target.maxhp/5?target.maxhp/5:0)" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_BODY ( NECROMANROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_WEAPON ( STAFF4 ) 

SET_MONSTER( DraconisGuardianNPC ) 
MOB_APPEARANCE					(  DRACONIS_LEATHER ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( PEACE )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 50000 )
MOB_AC                          ( 0 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CAN_ATTACK       (FALSE)

SET_MONSTER( CarmanNPC ) 
MOB_NPC_APPEARANCE				( FEMALE_PUPPET )
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 6500 )
MOB_DODGE_SKILL                 ( 410 )
MOB_AC                          ( 50 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 73981 )
MOB_STR                         ( 115 )
MOB_DEX                         ( 104 )
MOB_END                         ( 104 )
MOB_INT                         ( 135 )
MOB_WIS                         ( 104 )
MOB_WIL                         ( 104 )
MOB_LCK                         ( 35 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 100 )
MOB_WATER_RESIST      ( 100 )
MOB_AIR_RESIST        ( 100 )
MOB_EARTH_RESIST      ( 100 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 100 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 1210 )
MOB_ATTACK_DMG_ROLL   (	"1d172+134" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_BODY ( NECROMANROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_SHIELD ( BAROSSA_SHIELD )
MOB_DRESS_CAPE ( SERAPH_BLACK_WINGS )


SET_MONSTER( CarmanSpawnerNPC ) 
MOB_NPC_APPEARANCE				( FEMALE_PUPPET )
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 115 )
MOB_DEX                         ( 104 )
MOB_END                         ( 104 )
MOB_INT                         ( 135 )
MOB_WIS                         ( 104 )
MOB_WIL                         ( 104 )
MOB_LCK                         ( 35 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CAN_ATTACK       (FALSE)

MOB_DRESS_BODY ( NECROMANROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_SHIELD ( BAROSSA_SHIELD )

SET_MONSTER( WindhowlSentryNPC ) 
MOB_NPC_APPEARANCE				( PUPPET )
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 100000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 115 )
MOB_DEX                         ( 104 )
MOB_END                         ( 104 )
MOB_INT                         ( 135 )
MOB_WIS                         ( 104 )
MOB_WIL                         ( 104 )
MOB_LCK                         ( 35 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_DRESS_BODY ( CHAIN_BODY )
MOB_DRESS_FEET ( PLATE_BOOT )
MOB_DRESS_GLOVES ( LEATHER_GLOVE) 
MOB_DRESS_HELM ( CHAIN_COIF )
MOB_DRESS_LEGS ( CHAIN_LEGS )
MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_SHIELD ( ROMAN_SHIELD )

SET_MONSTER( DoppelgangerNPC ) 
MOB_NPC_APPEARANCE				( PUPPET )
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 50000 )
MOB_DODGE_SKILL                 ( 0 )
MOB_AC                          ( 0 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 115 )
MOB_DEX                         ( 104 )
MOB_END                         ( 104 )
MOB_INT                         ( 135 )
MOB_WIS                         ( 104 )
MOB_WIL                         ( 104 )
MOB_LCK                         ( 35 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 100 )
MOB_WATER_RESIST      ( 100 )
MOB_AIR_RESIST        ( 100 )
MOB_EARTH_RESIST      ( 100 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 100 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 65535 )
MOB_ATTACK_DMG_ROLL   (	"target.maxhp/(5*target.viewflag(30419)+1d5)" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_BODY ( NECROMANROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_CAPE ( SERAPH_BLACK_WINGS )

SET_MONSTER( FilandriusNPC ) 
MOB_NPC_APPEARANCE              ( PUPPET ) 
MOB_AGRESSIVNESS                ( -100 )
MOB_CLAN                        ( PEACE )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 1000000 )
MOB_DODGE_SKILL                 ( 65535 )
MOB_AC                          ( 1000000 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 0 )
MOB_STR                         ( 20 )
MOB_DEX                         ( 24 )
MOB_END                         ( 22 )
MOB_INT                         ( 20 )
MOB_WIS                         ( 21 )
MOB_WIL                         ( 25 )
MOB_LCK                         ( 22 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )

MOB_CAN_ATTACK       (FALSE)

MOB_DRESS_BODY ( ARMOREDROBE )
MOB_DRESS_FEET ( LEATHER_BOOTS )
MOB_DRESS_WEAPON ( STAFF4 ) 

SET_MONSTER( AnthorTheMadNPC ) 
MOB_NPC_APPEARANCE				( PUPPET )
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 6500 )
MOB_DODGE_SKILL                 ( 410 )
MOB_AC                          ( 50 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 73981 )
MOB_STR                         ( 115 )
MOB_DEX                         ( 104 )
MOB_END                         ( 104 )
MOB_INT                         ( 135 )
MOB_WIS                         ( 104 )
MOB_WIL                         ( 104 )
MOB_LCK                         ( 35 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 100 )
MOB_WATER_RESIST      ( 100 )
MOB_AIR_RESIST        ( 100 )
MOB_EARTH_RESIST      ( 100 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 100 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 1210 )
MOB_ATTACK_DMG_ROLL   (	"1d172+134" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_BODY ( LEATHER_ARMOR )
MOB_DRESS_FEET ( LEATHER_BOOTS )
MOB_DRESS_LEGS ( LEATHER_PANTS )
MOB_DRESS_SHIELD ( BAROSSA_SHIELD )
MOB_DRESS_CAPE ( REDCAPE )

SET_MONSTER( JormungandNPC ) 
MOB_NPC_APPEARANCE				( PUPPET )
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 100 )
MOB_HP                          ( 6500 )
MOB_DODGE_SKILL                 ( 410 )
MOB_AC                          ( 50 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 73981 )
MOB_STR                         ( 115 )
MOB_DEX                         ( 104 )
MOB_END                         ( 104 )
MOB_INT                         ( 135 )
MOB_WIS                         ( 104 )
MOB_WIL                         ( 104 )
MOB_LCK                         ( 35 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 100 )
MOB_WATER_RESIST      ( 100 )
MOB_AIR_RESIST        ( 100 )
MOB_EARTH_RESIST      ( 100 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 100 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 1210 )
MOB_ATTACK_DMG_ROLL   (	"1d172+134" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_DRESS_BODY ( NECROMANROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_SHIELD ( BAROSSA_SHIELD )
MOB_DRESS_CAPE ( SERAPH_BLACK_WINGS )

SET_MONSTER( HarvesterOfLifeNPC ) 
MOB_NPC_APPEARANCE				( PUPPET )
MOB_AGRESSIVNESS                ( 100 )
MOB_CLAN                        ( JARKO )
MOB_LEVEL                       ( 150 )
MOB_HP                          ( 12700 )
MOB_DODGE_SKILL                 ( 610 )
MOB_AC                          ( 75 )
MOB_XP_PER_HIT                  ( 0 )
MOB_XP_DEATH                    ( 34954 )
MOB_STR                         ( 165 )
MOB_DEX                         ( 149 )
MOB_END                         ( 149 )
MOB_INT                         ( 195 )
MOB_WIS                         ( 149 )
MOB_WIL                         ( 149 )
MOB_LCK                         ( 45 )               

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 200 )
MOB_WATER_RESIST      ( 200 )
MOB_AIR_RESIST        ( 200 )
MOB_EARTH_RESIST      ( 200 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 200 )

MOB_CREATE_PHYSICAL_ATTACK               
MOB_ATTACK_SKILL        ( 1210 )
MOB_ATTACK_DMG_ROLL   (	"1d258+202" )
MOB_ATTACK_PERCENTAGE   ( 100 )

MOB_CREATE_SPELL_ATTACK( 0, 20 )
MOB_ATTACK_SPELL( 10708 )
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 0, 20 )
MOB_ATTACK_SPELL( 10709 )
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 0, 20 )
MOB_ATTACK_SPELL( 10710 )
MOB_ATTACK_PERCENTAGE( 25 )
MOB_CREATE_SPELL_ATTACK( 0, 20 )
MOB_ATTACK_SPELL( 10618 )
MOB_ATTACK_PERCENTAGE( 25 )

MOB_DRESS_BODY ( NECROMANROBE )
MOB_DRESS_FEET ( BLACKLEATHER_BOOT )
MOB_DRESS_WEAPON ( BATTLE_SWORD )
MOB_DRESS_SHIELD ( BAROSSA_SHIELD )
MOB_DRESS_CAPE ( SERAPH_BLACK_WINGS )

SET_MONSTER( SpellPortalNPC )
MOB_AGRESSIVNESS      ( -100 ) 
MOB_OBJ_APPEARANCE    ( PORTAL )
MOB_CLAN              ( PEACE ) 
MOB_HP                ( 1101000 )
MOB_DODGE_SKILL       ( 65535 )
MOB_AC                ( 1000 )
MOB_LEVEL             ( 100 )
MOB_XP_PER_HIT        ( 0 )
MOB_XP_DEATH          ( 0 )
MOB_MIN_GOLD          ( 0 )
MOB_MAX_GOLD          ( 0 )
MOB_STR               ( 500 )
MOB_DEX               ( 500 )
MOB_END               ( 500 )
MOB_INT               ( 500 )
MOB_WIS               ( 500 )
MOB_WIL               ( 500 )
MOB_LCK               ( 500 )

MOB_FIRE_POWER        ( 100 )
MOB_WATER_POWER       ( 100 )
MOB_AIR_POWER         ( 100 )
MOB_EARTH_POWER       ( 100 )
MOB_LIGHT_POWER       ( 100 )
MOB_DARK_POWER        ( 100 )

MOB_FIRE_RESIST       ( 5000 )
MOB_WATER_RESIST      ( 5000 )
MOB_AIR_RESIST        ( 5000 )
MOB_EARTH_RESIST      ( 5000 )
MOB_LIGHT_RESIST      ( 5000 )
MOB_DARK_RESIST       ( 5000 )
MOB_CAN_ATTACK        ( FALSE )

	CreateNPC();
CLOSE_MONSTER_STAT_SETUP
		
void MonsterStatDestroy(){
}




